### ISSUE TITLE
[Errno 20] Not a directory: django-registration-redux 1.2

### ISSUE THREAD

**Issue by shgandhi** [macropin/django-registration#103]
Getting the error below on "python manage.py runserver". Tried django-registration redux version 1.2, on django 1.8.2 and python 3.4. Is there a workaround for this?
 <pre><code>[Errno 20] Not a directory: '/webapp>/virtualenv/lib/python3.4/site-packages/django_registration_redux-1.2-py3.4.egg/registration/migrations'</code></pre>

**Comment by dicato** [comment]
How did you install django-registration-redux?

**Comment by shgandhi** [comment]
Downloaded the tar file from Python Package Index - installed using 'python setup.py install.
Also tried using version 1.3 downloaded from github, and installed the same way.

**Comment by dicato** [comment]
From the error, it looks like you are installing in a virtualenv? Is that true? Can you open that virtualenv's Python interpreter and `import registration`?

Before using the package in your Django project, you will need to sync and migrate the database as well.

**Comment by Suede323324** [comment]
I also have this issue, and I can  import registration

**Comment by dicato** [comment]
Interesting. The issue is not obvious to me. I'll try to re-create locally and will report back.

**Comment by dicato** [comment]
@shgandhi & @Suede323324 are you seeing this error on new installation of drr or upgrading drr for a project already using it?

**Comment by dicato** [comment]
Interesting. I was able to re-produce the issue by installing drr from source instead of using `pip`.

While I figure out why that is happening, install using `pip` in the meantime as a workaround if possible.

**Comment by dicato** [comment]
I've put up #104 to address this issue.

**Comment by Suede323324** [comment]
Thanks dicato :+1: !But now,would I remove the  directory :/usr/local/lib/python2.7/dist-packages/django_registration_redux-1.2-py2.7.egg, and reinstall the django-registration-redux

**Comment by dicato** [comment]
@Suede323324 you can delete those files and re-install. You will either need to pull the branch in #104 or use `python setup.py develop` as a workaround while that pull request is being reviewed and eventually lands in the next release.

**Comment by shgandhi** [comment]
Thanks @dicato :smiley: 
Used <code>python setup.py develop</code> to reinstall registration redux, works perfectly!
