### ISSUE TITLE
RegistrationView.register method doesn't know how to get site object properly

### ISSUE THREAD

**Issue by arpitremarkable** [macropin/django-registration#106]
Piece of code that is currently (in 1.2) to get current Site object
```python
    if Site._meta.installed:
        site = Site.objects.get_current()
    else:
        site = RequestSite(request)
```
This is creating problem in my situation where I have Site framework installed but don't have SITE_ID defined in my settings(it's set to None) as I'm relying on my `request.get_host()` to fetch me the correct Site object (using subdomains).. And that is why `RequestSite(request)` works fine for me, but not `Site.objects.get_current()`
.
P.S: Exception that I get.. `*** ImproperlyConfigured: You're using the Django "sites framework" without having set the SITE_ID setting. Create a site in your database and set the SITE_ID setting or pass a request to Site.objects.get_current() to fix this error.`

**Comment by arpitremarkable** [comment]
Any reviewers?

**Comment by dicato** [comment]
I will review. Thanks for filing the issue and making a PR.
