### ISSUE TITLE
Manual validation from the admin

### ISSUE THREAD

**Issue by areski** [macropin/django-registration#109]
This is proposition for a new feature, the idea is that the admin have to manually accept the new registered user before they are allowed to register.

So after registration and mail validation the user, get on a view with "Your account is being review, we will confirm it shortly!"

Maybe a similar feature can be achieve with a workaround?

**Comment by dicato** [comment]
Considering I've built that exact workflow in the past, I agree it's a useful feature.

Could you take a look at [django-allauth](https://github.com/pennersr/django-allauth) and determine whether that workflow is already supported?

**Comment by areski** [comment]
As far as I could see that workflow doesn't seem to be supported in django-allauth

**Comment by dicato** [comment]
Thanks for doing the research.

If you work on a pull request, I'm happy to provide input and review. I will say that after using that workflow in production, we eventually moved away from it as it created a very high barrier of entry for adoption of our services, which was leading to us losing users. Just food for thought. There are absolutely use cases for this.

**Comment by areski** [comment]
I understand that  in most cases this is not the willing behavior. Usually I don't want this, but in one of my scenario -I work in VoIP and payment- we want to run a manual verification on new user to reduce fraud risks.

I will send a PR as soon as this comes back to my priority list.

**Comment by lucbran** [comment]
This is something I am also interested...any update?

**Comment by joshblum** [comment]
@areski are you still interested in working on this?

**Comment by areski** [comment]
@joshblum I didn't start anything in that area, but I would love to see a PR so if you want to take over and propose a patch please go ahead.

**Comment by joshblum** [comment]
@areski I don't have time right now to submit a patch myself, but just wanted to see if the issue was current. Since the feature is pretty specific, I think ti would be best to close the issue for now and reopen if someone submits a PR.

**Comment by dicato** [comment]
@joshblum I'd leave the issue open and slap the "help wanted" label on it since the feature request is still valid.

**Comment by joshblum** [comment]
sounds good!

**Comment by joshblum** [comment]
closed by #184
