### ISSUE TITLE
High failure-rate of Django-registration in slow mobile internet environment

### ISSUE THREAD

**Issue by mhb11** [macropin/django-registration#114]
@macropin 
I have a text-based app that lets users in low-resource localities communicate with one another over extremely flaky mobile internet (GPRS). It's being used in villages in South Asia, by people who can't afford great devices nor live in localities with robust coverage.  

My app utilizes django-registration to enable basic registration. I'm getting a complaint from ~50% of my users that registration fails in the app (we've extensively tested its robustness on our end). By failure they mean typing out the necessary fields and pressing register, only for the 'webpage not found' page to result. 

My app's inbuilt features (e.g. posting messages) are doing fine; registrations is the only one that is seeing an elevated complaint rate. Can there be any correlation between django-registration failing and slow mobile internet? Being a core contributer to this project, maybe you can send some pearls of wisdom my way. I'll be grateful. We really need a solution.

**Comment by dicato** [comment]
Have you been able to consistently reproduce the issue? If so, could you tell me some steps and I can try to reproduce? Specifically which piece of the registration process is failing?

**Comment by dicato** [comment]
@mhb11 is this still an issue? The latest release changes the models and logic related to activation and may help solve your problem.

I'm closing this and will re-open accordingly.
