### ISSUE TITLE
Terms of service is missing from documentation

### ISSUE THREAD

**Issue by soulraven** [macropin/django-registration#116]
How to use TOS in a registration form?
Any point from this is missing how to integrate in django template

**Comment by soulraven** [comment]
anyone? how to include this element inside the form?

**Comment by dicato** [comment]
The form will be passed into the appropriate views as part of the context. You can render the form as you would any other variable in the context. For example:

```html
<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
```

Using the TOS Form will include a checkbox that must be checked during registration.

Does that make sense?

**Comment by soulraven** [comment]
ok, but if i want to add manually that field? how i do that, because i don't know what is the schema for form var

**Comment by dicato** [comment]
You need to write your own custom HTML if you choose to do that. I'd refer to Django's documentation on forms. https://docs.djangoproject.com/en/1.8/topics/forms/
