### ISSUE TITLE
Reverse for 'registration_activate' not found

### ISSUE THREAD

**Issue by 5ak3t** [macropin/django-registration#119]
I have the following settings - 

`REGISTRATION_OPEN = True                # If True, users can register`

`ACCOUNT_ACTIVATION_DAYS = 7     # One-week activation window; you may, of course, use a different value.`

`REGISTRATION_AUTO_LOGIN = True  # If True, the user will be automatically logged in.`

`LOGIN_REDIRECT_URL = '/'  # The page you want users to arrive at after they successful log in`

`LOGIN_URL = '/accounts/login/'  # The page users are directed to if they are not logged in, and are trying to access pages requiring authentication`

`INCLUDE_REGISTER_URL = True`

And the following in the URLS - 

`...`
  `url(r'accounts/register/', BaseRegisterView.as_view(), name='registration_register'),`
    `(r'^accounts/', include('registration.backends.simple.urls')),`
`...`

Following error - 

    Reverse for 'registration_activate' with arguments '('c6ae1dfec24759f7cd8013462c7240f0f21440aa',)'     and keyword arguments '{}' not found. 0 pattern(s) tried: []

    Error during template rendering

    In template /Users/Saket/.virtualenvs/oss/lib/python2.7/site-  packages/registration/templates/registration/activation_email.txt, error at line 13
    
    Reverse for 'registration_activate' with arguments '('c6ae1dfec24759f7cd8013462c7240f0f21440aa',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
    3	{% blocktrans with site_name=site.name %}
    4	You (or someone pretending to be you) have asked to register an account at
    5	{{ site_name }}.  If this wasn't you, please ignore this email
    6	and your address will be removed from our records.
    7	{% endblocktrans %}
    8	{% blocktrans %}
    9	To activate this account, please click the following link within the next
   
     10	{{ expiration_days }} days:
     11	{% endblocktrans %}
  
          http://{{site.domain}}
          {% url 'registration_activate' activation_key %}

**Comment by dicato** [comment]
@5ak3t is this still valid?

**Comment by joshblum** [comment]
@5ak3t any updates? If not we'll close the issue for now, feel free to reopen if you're still having any problems!

**Comment by 5ak3t** [comment]
Please close it for now.

**Comment by joshblum** [comment]
Thanks @5ak3t!

**Comment by shepelevstas** [comment]
cant get {% url 'registration_activate' %} part to work in activation_email.txt
is there a solution?

**Comment by joshblum** [comment]
@5ak3t were you able to find a workaround?

**Comment by shepelevstas** [comment]
had to construct it:
http://{{site}}/accounts/activate/{{activation_key}}

**Comment by joshblum** [comment]
@shepelevstas how did you include the urls? perhaps that's why the reverse failed?

**Comment by shepelevstas** [comment]
url(r'^accounts/register/$',
        RegistrationView.as_view(form_class=UserRegistrationForm),
        name="registration_register",
        ),
    url(r'^accounts/activate/(?P<activation_key>[-:\w]+)/$',
        ActivationView.as_view(),
        name='registration_activate'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),

**Comment by shepelevstas** [comment]
sorry, don't know how to format text to code here

**Comment by joshblum** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for formatting :)

also i think that you're using the [django-registration](https://github.com/ubernostrum/django-registration/) project since you have `url(r'^accounts/', include('registration.backends.hmac.urls')),` and not this one (django-registration-redux). You should open the issue there if they have a bug!

**Comment by shepelevstas** [comment]
Wow! That's a facepalm )))))))))) Thanks!:)

**Comment by surfer190** [comment]
You will run into this issue if you have given to namespace to the apps `urls.py` and within that you are including `'registration.backends.default.urls'`

So your app finds `users:registration_activate` but not just `registration_activate`
