### ISSUE TITLE
Custom User Registration Model?

### ISSUE THREAD

**Issue by alzearafat** [macropin/django-registration#120]
Hi,

I am a new kid on django/python and your application, so please bear with me :)
First, I want to thank you for this very useful application. Really helped me a lot :)

Now I'm trying to add custom User model fields to registration profile. Something like Facebook URL, Email, profile pic, etc...

How is the simplest way to do so? 

Any enlightenment would be greatly appreciated.

Please excuse my English,
Thanks in advance :)

**Comment by dicato** [comment]
@alzearafat I actually went through this same design process. My first approach was to save the additional information on the `RegistrationProfile` model. After a bunch of iterations, I came to the realization that it makes far more sense to follow Django's guidance and create the equivalent of a `UserProfile` or `GroupProfile` model, foreign keyed back to `User` or `Group` accordingly, to save that information.

See this issue for background: https://github.com/macropin/django-registration/issues/18
