### ISSUE TITLE
Fail to change the template of registration page 

### ISSUE THREAD

**Issue by rylanchiu** [macropin/django-registration#122]
I have put the registration folder on the root directory and create two files: registrationform.html and registrationcomplete.html but the outlooking still doesn't change.
Could you please help me solve this problem.

**Comment by dicato** [comment]
Template names must match what is included in the package. See [this directory](https://github.com/macropin/django-registration/tree/332b38d4c4c8749bdab7b0c53906a13975d08fcc/registration/templates/registration).

The templates should be named `registration_complete.html` and `registration_form.html`.

**Comment by rylanchiu** [comment]
Thank you very much! @dicato  But one more problems. Why I can still visit the register page after I log in ?

**Comment by dicato** [comment]
You're welcome! :smile: 

Nothing prevents an authenticated user from hitting the registration page. There is an open issue discussing this - https://github.com/macropin/django-registration/issues/96
