### ISSUE TITLE
How to add avatar upload 

### ISSUE THREAD

**Issue by rylanchiu** [macropin/django-registration#123]
I want to enable the users to upload their avatars on the registration page, how can I do that?

**Comment by dicato** [comment]
In my opinion, you want to save that type of information on a custom `UserProfile` model that has a one-to-one relationship with `User`.

For simplicity, keep registration separate from collecting that type of information. Upon registering and authenticating, you can present the user with a set of views to configure their profile.

**Comment by rylanchiu** [comment]
@dicato  Tons of thanks for you help and time. Have you tried django-avatar? If not, what tools do you use for the avatar management?

**Comment by dicato** [comment]
I don't have a recommendation for managing avatars. Sorry! I would consider something like [Gravatar](https://en.gravatar.com/) if an external service is acceptable.

**Comment by rylanchiu** [comment]
Thank you very much @dicato !
