### ISSUE TITLE
Add custom password reset form and etc

### ISSUE THREAD

**Issue by stiig** [macropin/django-registration#124]
Please, add to SETTINGS custom class for password reset form, password change form and offer. To be able to override form.

**Comment by dicato** [comment]
Could you clarify what you are trying to do?

If you want to customize the template, you can override all of the packaged defaults [found here](https://github.com/macropin/django-registration/tree/332b38d4c4c8749bdab7b0c53906a13975d08fcc/registration/templates/registration).

**Comment by stiig** [comment]
I need add placeholder to password reset form, password change form and other. I'm already override all template, but i can't override tag `<input>` on the form, than add placeholder `<input placeholder='Email'>`. I solve it is adding a route
```
url(r'^accounts/password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': reverse_lazy('auth_password_reset_done'),
         'password_reset_form': MyPasswordResetForm},
        name='auth_password_reset'),
```
But, i think it's "dirty" solution, not? Or it's right way - disabled INCLUDE_AUTH_URLS, and sets route manually with MyForm?

P.S. Sorry for my English, and thank's for your answers

**Comment by stiig** [comment]
But, if i have setting, e.g. `PASSWORD_RESET_FORM` i could set simplify in settings
```
PASSWORD_RESET_FORM = MyPasswordResetForm
PASSWORD_CHANGE_FORM = MyPasswordChangeForm
...
```

**Comment by dicato** [comment]
I think your solution is good enough. It is less custom code and less overriding of Django built in views and forms.

In my opinion, the `settings` approach you describe is more suited for addition to Django itself instead of this package.
