### ISSUE TITLE
Non-matching passwords are not passed back to form

### ISSUE THREAD

**Issue by alper** [macropin/django-registration#127]
I'm working with django-registration-redux in a project and I'm noticing that if both passwords match, they are both reflected back to the user in cleaned_data (when there are other errors):

```{'password1': u'bla', 'password2': u'bla'```

but if they don't match then only password1 is sent back.

Both of those seem weird behaviour but it would be consistent to send both values back in both cases.

**Comment by joshblum** [comment]
@alper  is this still an issue? From the current Django source: https://github.com/django/django/blob/master/django/contrib/auth/forms.py#L70 it doesn't seem like there is any special action to only send back one password. What version of django/django-registration-redux are you using?

**Comment by dicato** [comment]
Related (maybe duplicate) to #129

**Comment by joshblum** [comment]
Closing for now (assuming #129 fixed the problem)
