### ISSUE TITLE
Documentation issue regarding mismatching passwords

### ISSUE THREAD

**Issue by srenatus** [macropin/django-registration#128]
In [docs/forms.rst](https://github.com/macropin/django-registration/blob/c3dd438a2c8a4b3225d9661a45ea5ef9833d3fd4/docs/forms.rst), it states:

> Because it does not apply to any single field of the form, the validation error for mismatched passwords is attached to the form itself, and so must be accessed via the form's `non_field_errors()` method.

However, the error is actually attached to `password2`, [e.g. see tests](https://github.com/macropin/django-registration/blob/c3dd438a2c8a4b3225d9661a45ea5ef9833d3fd4/registration/tests/forms.py#L48-L53)

**Comment by dicato** [comment]
Closing. This was fixed and the issue was left open.
