### ISSUE TITLE
Problem with Django 1.9  

### ISSUE THREAD

**Issue by GDAproj** [macropin/django-registration#130]
In git master with import RequestSite is all ok,but when installing django-registration-redux via pip i obtain version with code that incompatible with django 1.9 because import RequestSite from django.contrib.sites.models.

**Comment by dicato** [comment]
We need to make a new release and publish it to PyPI.

**Comment by macropin** [comment]
@dicato Are you able to coordinate the release? If you let me know when it's tagged and I'll push to PyPi.

**Comment by dicato** [comment]
I'd certainly like to help. Time during December is a bit of a challenge! @macropin I've filed an issue for us to discuss a 1.3 release. #131

@GDAproj please install from source for the time being. I'm going to close this issue.
