### ISSUE TITLE
Old version package in pypi

### ISSUE THREAD

**Issue by ckcnik** [macropin/django-registration#138]
https://pypi.python.org/pypi/django-registration-redux/

I am execute comand: pip install -v django-registration-redux

I get an answer:
Collecting django-registration-redux
  Getting page https://pypi.python.org/simple/django-registration-redux/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/django-registration-redux/ HTTP/1.1" 200 255
  1 location(s) to search for versions of django-registration-redux:
  * https://pypi.python.org/simple/django-registration-redux/
  Getting page https://pypi.python.org/simple/django-registration-redux/
  Analyzing links from page https://pypi.python.org/simple/django-registration-redux/
    Found link https://pypi.python.org/packages/source/d/django-registration-redux/django-registration-redux-1.1.tar.gz#md5=c7cc0e1b21684fb12dff4f3ae94d4900 (from https://pypi.python.org/simple/django-registration-redux/), version: 1.1
    Found link https://pypi.python.org/packages/source/d/django-registration-redux/django-registration-redux-1.2.tar.gz#md5=c23df8c5ea781a33e8cb734a4007c978 (from https://pypi.python.org/simple/django-registration-redux/), version: 1.2
  Using version 1.2 (newest of versions: 1.2, 1.1)
  Using cached wheel link: file:///home/denis/.cache/pip/wheels/c0/64/55/3bc77179ce8d18a2d2444448f2e4ee465e2a064dd063cc533d/django_registration_redux-1.2-py3-none-any.whl
Installing collected packages: django-registration-redux

Successfully installed django-registration-redux-1.2
Cleaning up...

This link contain old package: https://pypi.python.org/packages/source/d/django-registration-redux/django-registration-redux-1.2.tar.gz#md5=c23df8c5ea781a33e8cb734a4007c978

Please, load a new version package in pypi.

**Comment by dicato** [comment]
We are working towards a 1.3 release. See here: https://github.com/macropin/django-registration/issues/131
