### ISSUE TITLE
how to fix RequestSite issue.

### ISSUE THREAD

**Issue by rajan-github** [macropin/django-registration#139]
RequestSite is no longer in django.contrib.sites.models but is in django.contrib.sites.requests. I found that when I installed django-registration-redux, those old import statements are still there. So it raises ImportError. So how to fix it? How to replace "RequestSite" in the admin.py? please help

**Comment by dicato** [comment]
@rajan-github please install from source for now. That issue is fixed in the master branch but not in an official release yet. You can also see the prior conversation in #132

Thanks
