### ISSUE TITLE
Custom user

### ISSUE THREAD

**Issue by VDenis** [macropin/django-registration#14]
How provide a custom user, with addition fields (age or date born, id). Previous i use this model:
class People(models.Model):
    user = models.OneToOneField(User)l
    born = models.DateField() # born date

class Professor(People): # Ingeritance
    identification_card = models.CharField(max_length=75)
    department = models.CharField(max_length=75)
    
    def __unicode__(self):
        return "Professor" + self.user.name + ' ' + self.user.surname

    def get_absolute_url(self):
        return "/professor/%i/" % self.id

**Comment by macropin** [comment]
Assumptive closure.
