### ISSUE TITLE
Request object missing when "Re-send e-mail" function is triggered from the admin

### ISSUE THREAD

**Issue by alorence** [macropin/django-registration#146]
In the admin, when the activation mail is re-sent to some users using the corresponding function, the 'request' object is not passed to the function (see https://github.com/macropin/django-registration/blob/master/registration/admin.py#L44).
Is it a normal behavior ? I don't know if passing the request object could be a security issue, but not having it lead to different rendering of the e-mail template:

    {{ request.scheme }}://{{ site.domain }}{% url 'registration_activate' activation_key %}

becomes:

    https://www.website.com/activation/7aa2f014b2a3aac1cc75afffe720de9d663bfda7/

in the normal registration procedure but

    ://www.website.com/activation/7aa2f014b2a3aac1cc75afffe720de9d663bfda7/

when the mail is re-sent from the admin.

As a workaround, I used 'default' filter;

    {{ request.scheme|default:'http' }}

but it is not enough generic in some case (for example, one of our website is served in https for almost all users but http for users with very old or outdated configurations)

**Comment by dicato** [comment]
I like your workaround. A properly deployed web application should handle the TLS redirection.

**Comment by dicato** [comment]
@alorence would you be willing to turn your work around into a pull request?

**Comment by alorence** [comment]
Yes of course. I would prefer give the request object as a parameter for  `resend_activation_mail` from the `RegistrationAdmin` class, instead of just add a default filter to the template for that specific case. Do you agree?

**Comment by dicato** [comment]
That sounds like a good approach!

**Comment by alorence** [comment]
The pull request is now ok with unit tests, flake8 and coveralls checks. As a bonus, missing tests for admin commands have been added. Feel free to merge & close if your are ok with that work, or tell me if you would like I modify something.
Cheers

**Comment by dicato** [comment]
Fantastic! Thank you very much for adding the additional tests and doing the cleanup.
