### ISSUE TITLE
django admin templates in password change/reset dialogs

### ISSUE THREAD

**Issue by vvch** [macropin/django-registration#147]
Official docs recommend to place `registration` app above `django.contrib.admin` to use custom templates in user registration dialogs. But in this case custom templates also replace built-in ones in admin password change/reset forms (e.g. at /admin/password_change/ url) which is not always appropriate.
Is there any official way to use built-in admin templates in admin password forms and custom ones in  user password forms (at /accounts/password/change/ )? Maybe, it would be better to separate these templates, e. g. by renaming them?

**Comment by dicato** [comment]
Closed as duplicate to #99.
