### ISSUE TITLE
Release version 1.4

### ISSUE THREAD

**Issue by joshblum** [macropin/django-registration#149]
When will the next version be released? Version 1.3 has some frustrating problems with the variables of the `RegistrationView` since the signatures differ between the `views.RegistrationView` and `backends.default.views.RegistrationViews` classes. The code is also buggy (i.e. https://github.com/macropin/django-registration/blob/v1.3/registration/views.py#L45, which is missing the request variable in the call to `invalid_form`.)

These issues make it much more difficult to extend the code in the current version. It seems like most of these problems have been fixed on master, what is the timeline for pushing a new version to pypi however? Would love to help if there is any dev work that needs to be done to move things along :) Thanks for the awesome library! :D

**Comment by macropin** [comment]
You can help by sending us PR's with the bug fixes if they're not already fixed in master. That will help us get a release out sooner.

**Comment by joshblum** [comment]
Great, I'll submit a PR for #150, are there things in particular that you guys are waiting for to release 1.4 that still need fixing?

**Comment by dicato** [comment]
@joshblum nope, nothing in particular!

If we can get your three PRs reviewed and merged, I think we can push a 1.4 immediately after.

**Comment by joshblum** [comment]
Great! I'lll fix any comments as they come in, happy to help :)
