### ISSUE TITLE
Question: Where are the default files stored after pip install django-registration-redux

### ISSUE THREAD

**Issue by kellyzz** [macropin/django-registration#151]
After pip installed django-registration-redux, I need to modify the default forms.py file, but can not find it in directory, where are the default files stored? Thanks!

**Comment by dicato** [comment]
@kellyzz you should generally avoid editing installed packages and code and instead inherit from them and add your own functionality.

Import the forms you want to change and subclass them. You can do this in your own custom backend. Hopefully the docs are helpful on this topic: [backends](https://django-registration-redux.readthedocs.org/en/latest/default-backend.html) and [default forms](https://django-registration-redux.readthedocs.org/en/latest/forms.html)
