### ISSUE TITLE
PyPi readme not formatted correctly.

### ISSUE THREAD

**Issue by macropin** [macropin/django-registration#156]
Possibly related to PyPi RST parsing https://stackoverflow.com/questions/16367770/my-rst-readme-is-not-formatted-on-pypi-python-org

**Comment by dicato** [comment]
I suspect it's related to these changes:
https://github.com/macropin/django-registration/commit/6d9fc0c2a1a4f92a325ba0e823e0fbbd650f639d and

**Comment by dicato** [comment]
@joshblum do you have a moment to look at this?

**Comment by dicato** [comment]
Closing this issue. This will be fixed on PyPI when we push 1.5. :smile:
