### ISSUE TITLE
How to add group to a user

### ISSUE THREAD

**Issue by aj07mm** [macropin/django-registration#162]
Currently I couldn't find anything about assing a "group" to a user on the docs, how can this be done in the simples way possible? If not there should be a feature for that I think.

**Comment by dicato** [comment]
This project currently does not support any features related to creating groups and moving users into groups. I'd recommend [django-organizations](https://www.djangopackages.com/packages/p/django-organizations/) for your use case.

Alternatively, I would recommend manually creating groups and moving users into them if you don't need an automated solution.
