### ISSUE TITLE
How can I add more fields to the user form??

### ISSUE THREAD

**Issue by aj07mm** [macropin/django-registration#164]
Im freaking out on this, any help?

**Comment by dicato** [comment]
You can subclass the registration form you are using and add the fields you want. Checkout this discussion - https://github.com/macropin/django-registration/issues/73

If you want to pass additional data to the context, see this issue - https://github.com/macropin/django-registration/issues/91

Hopefully that helps.I'm closing the issue but feel free to ask more questions.

**Comment by aj07mm** [comment]
Thanks @dicato! Really saved my life

**Comment by dicato** [comment]
You're welcome!
