### ISSUE TITLE
get_success_url() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by den-is** [macropin/django-registration#167]
Trying substitute registration view with custom one for custom "success registration redirect url"
```python
class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        return '/rango/'
```
```
TypeError at /accounts/register/
get_success_url() takes exactly 3 arguments (2 given)
```
Running Django 1.8.11 and python 2.7.10
temporary substitued it with
```python
class MyRegistrationView(RegistrationView):
    success_url = '/rango/'
```
Can't debug which objects/arguments are not passed and who passes (or should pass) them to this function

This is part of  [Tango with django](http://www.tangowithdjango.com/book17/chapters/login_redux.html) tutorial

**Comment by dicato** [comment]
1.4 had a backward incompatible change that removed the (unnecessary) passing of `request` - see [here](https://github.com/macropin/django-registration/blob/24bf503cdbe4e97b7c1582d56305964a2ec45c50/CHANGELOG#L12).

I'd suggest discussing with the maintainers of the tangowithdjango book to update accordingly. https://github.com/leifos/tango_with_django_book

**Comment by ywang04** [comment]
Thanks a lot. Removing "request" is to fix the same issue.

**Comment by React-props** [comment]
@ywang04 https://unmarshallingbodily51.github.io/HPlXPslfjy4KUiqRVHb3o2frlhGH0KhgIivwTEptQu/
