### ISSUE TITLE
Changing registration activation email

### ISSUE THREAD

**Issue by lucbran** [macropin/django-registration#168]
Hi,
I need to make modifications to registration email sent automatically to the user, but the template txt doesnt show the complete email text (for example cannot find anywhere "You (or someone pretending to be you) have asked to register an account at example.com. If this wasn't you, please ignore this email and your address will be removed from our records. )
Someone can tell me where can I midify this email text? thanks

**Comment by dicato** [comment]
You can override the templates used to send those emails: https://django-registration-redux.readthedocs.org/en/latest/quickstart.html#templates

Specifically, you will want to override `registration/activation_email_subject.txt`, `registration/activation_email.txt`, and `registration/activation_email.html` if you are sending HTML emails.

**Comment by lucbran** [comment]
Hello Stephen
thanks for your promt assistance!

**Comment by dicato** [comment]
You're welcome!

**Comment by lucbran** [comment]
I have a question:
I have installed Redux in my site (still on construction) and have seen templates for password change..
I havent found any link on where to set the password change…am I wrong’ thanks
Luca
