### ISSUE TITLE
document use of DEFAULT_FROM_EMAIL

### ISSUE THREAD

**Issue by puterleat** [macropin/django-registration#17]
This is a small thing, but it would be nice to document the use of DEFAULT_FROM_EMAIL and/or allow this to be set differently from the standard django setting. Perhaps REGISTRATION_DEFAULT_FROM_EMAIL which is set to DEFAULT_FROM_EMAIL by default (!)

**Comment by macropin** [comment]
Could you please make the relevant changes to the documentation and submit a pull request.
