### ISSUE TITLE
Change account activation logic

### ISSUE THREAD

**Issue by joshblum** [macropin/django-registration#171]
Right now the expiration date on a `RegistrationProfile` is determined by `user.date_joined`, however in our workflow we sometimes create users before they actually go through the registration flow. As an alternative would it be possible to add a field to `RegistrationProfile` so that the activation key time can be independent of the `user.date_joined`. Happy to submit a PR, just wanted to run the strawman by you guys first :)

**Comment by dicato** [comment]
I don't see any obvious issues with the approach. You'll obviously need a schema migration. You'll probably need a data migration as well.

**Comment by joshblum** [comment]
Hmm a simpler alternative could be to update the `user.date_joined` in `RegistrationProfile.create_inactive_user`, this is our temporary workaround. Thoughts?

**Comment by dicato** [comment]
merged!
