### ISSUE TITLE
Migrations issue

### ISSUE THREAD

**Issue by JurajKavka** [macropin/django-registration#173]
Hello, 

i have project where i'm using registration-redux with custom user model. I have problem that my migrations won't run in initial installation. I think, that `registration` migrations runs before `accounts` migrations and i'm getting

```
django.db.utils.ProgrammingError: relation "accounts_user" does not exist
```

What is really strange for me is that i don't see `migrations` directory in `..../site-packages/registration/` directory. But if I comment out `registration` from INSTALLED_APPS, migrations runs OK. Then I uncomment `registration`, run migrations and something created `registrationprofile` table. :) I'm confused. But i wanto to try `run_before` clausule in my accounts initial migrations. (https://docs.djangoproject.com/en/1.9/howto/writing-migrations/#controlling-the-order-of-migrations)

Thank You for Your help.

J.

**Comment by dicato** [comment]
I think to fix this issue your migration needs to depend on the initial migration in `django.contrib.auth`. You can hopefully test this pretty easily.

As this is not an issue with django-registration directly, I'm closing this issue but feel free to ask any followup.

**Comment by iamunadike** [comment]
I have the same issue with Django 3 using django-tenants
