### ISSUE TITLE
Wrong status code returned on unsuccessful post request

### ISSUE THREAD

**Issue by kapilsdv** [macropin/django-registration#176]
Hi,

I am submitting user sign in form and in both the cases of passing correct and incorrect credentials i am getting status code 200 in response, I think this is not the desired behavior, it should return 400 in case of sign in failure.

Please suggest.

**Comment by dicato** [comment]
This is a question for Django directly. Django chooses to return a 200 in this scenario. You can see the source code here: https://github.com/django/django/blob/92107522ed3568740ec7c3597db50b5c3a6e84d3/django/contrib/auth/views.py#L98
