### ISSUE TITLE
ImportError on Heroku

### ISSUE THREAD

**Issue by fynn4coding** [macropin/django-registration#179]
I have an issue when I deploy my app into heroku. The repo was succesfully deployed. But, when I open the app (my `DEBUG` still `TRUE`) it says `ImportError No module named forms` and it comes from `from registration.forms import RegistrationFormUniqueEmail` that I make a custom validator to that. I don't know what I have to do because when I import `RegistrationFormUniqueEmail` itself on heroku bash manage.py shell it's nothing error. I don't know if it's the heroku issue or what. But, I wan't to know what's happen. Here's the app [https://glacial-wave-87412.herokuapp.com/](https://glacial-wave-87412.herokuapp.com/l). (My app don't have this issue on local).
[](url)
Thanks.

**Comment by dicato** [comment]
Could you provide the full exception log?
