### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by aakashq** [macropin/django-registration#180]
Is it possible to integrate this with djangorestframwork?

**Comment by dicato** [comment]
Integrate meaning register users over a RESTful API? Yes, that's possible; django-registration would provide the model (`RegistrationProfile`) and django-rest-framework would provide the `ViewSets`, routes, etc.

I'm a very big fan of django-allauth as a more complete, easier to adopt, and easier to maintain as a consumer solution for registration and managing Users in Django applications. I did a quick search and there is a package that aims to integrate django-allauth with django-rest-framework: https://github.com/Tivix/django-rest-auth

If are adopted a solution for registration, I would highly advocate you look at django-allauth. If you are already using django-registration, I'm more than happy to review and accept pull requests for this feature!

**Comment by joshblum** [comment]
Closing this issue for now in favor of migration to django-allauth
