### ISSUE TITLE
how to handle email uniqueness

### ISSUE THREAD

**Issue by dicato** [macropin/django-registration#183]
Leftover from #161

Emails are not required to be unique by default. How should we handle email uniqueness when it comes to trying to resend an activation code?

**Comment by joshblum** [comment]
It seems bad to send an activation email to multiple users who have the same email. We could add a filter for inactive/valid reg keys and if there are still multiple objects just `return False` to be safe

**Comment by dicato** [comment]
I agree on handling the error scenario more specifically.

I suspect we should also add something to the documentation about only supporting unique email addresses.
