### ISSUE TITLE
Using Two Factor authentication with registration module

### ISSUE THREAD

**Issue by maxcanada** [macropin/django-registration#186]
Hi, 

I am not sure where to ask this, but I can't find anything on the internet.
Did any of you had to use a two factor authentication with the registration module ?
If yes, can you point me to some documentation or give me some info ?

Thanks a lot

**Comment by dicato** [comment]
django-registration does not support two-factor. To the best of my knowledge, there is not a pluggable two-factor project that works with django-registration.

I'd strongly suggest looking at [django-allauth](https://github.com/pennersr/django-allauth) and [django-allauth-2fa](https://github.com/valberg/django-allauth-2fa). You may want to consider using [this fork of django-allauth-2fa](https://github.com/percipient/django-allauth-2fa) which is maintained by our engineering team at work.

I'm closing this issue but please continue the conversation here.

**Comment by maxcanada** [comment]
Hi, 

Thanks a lot for your answer ! 

I think I am going to go with [https://github.com/Bouke/django-two-factor-auth](https://github.com/Bouke/django-two-factor-auth)

They have a great example app and the code is provided in the examples folder.

One problem might be to migrate existent users registered with the registration module to the new system.
Any suggestion? :)

**Comment by dicato** [comment]
Note the warning about being unmaintained and not "production ready" - [see here](https://github.com/Bouke/django-two-factor-auth/blob/9ec5b1de6e9e2fa12bbea0ad2d5ddb248a39a0e3/README.rst)!

----

I used to use that project with django-registration and it was one of the reasons why we migrated to django-allauth and django-allauth-2fa.

**Comment by maxcanada** [comment]
Alright you got it ;) I am going to try allauth and allauth-2fa first!
Thanks for the help, I appreciate it. I'll post anything relevant in this thread.

**Comment by dicato** [comment]
👍 Happy to help.

**Comment by maxcanada** [comment]
Hey, 

I got allauth up and running quite easily (no need to even migrate the users :)). But can't seem to install the allauth-2fa through the regular process.
`pip install django-allauth-2fa` gives me that error:

> 
> Could not find a version that satisfies the requirement django-allauth-2fa (from versions: )
> No matching distribution found for django-allauth-2fa

I tried by cloning the project and running setup.py install, it works, but then when I try to run the website it says :
No module named allauth_2fa

Do you have any idea ?
Thanks again for your help, savior ! ;)

**Comment by dicato** [comment]
First, you may want to consider using this fork: https://github.com/percipient/django-allauth-2fa

(I work there. :smile:) We are working on getting the changes merged back. You can install it via:
```

**Comment by dicato** [comment]
@maxcanada by the magic of the Internet, Percipient is now the official maintainer of django-allauth-2fa: https://github.com/percipient/django-allauth-2fa

**Comment by maxcanada** [comment]
Haha thanks dicato, 

I got it working using your link. However, I had to upgrade the django-otp module to 0.3.5 otherwise I was getting a "Apps aren't loaded yet" exception.

Thanks for the help, I'll test that out right away and let you know ;)

**Comment by dicato** [comment]
👍

**Comment by maxcanada** [comment]
Hey Dicato, 

Everything ran quite smoothly. I set up all the pages and the process is quite clear.

A few questions though:
- Is it possible to have a system (maybe a decorator ?) to select the pages that are protected by the 2FA ? Are you planning to do that or should I try myself ?
- When I log in (having 2FA enabled), I land on the authenticate page. Which is normal. but then if I try to click on the link to disable the 2FA, I got a 500 error `AttributeError: 'AnonymousUser' object has no attribute 'totpdevice_set'`
- While logged in but not yet input the 2FA code yet (so, on the authenticate page), when I try to access another URL, it directly logs me out. This is not a behavior that I want. I want to display the authenticate page again. How would you do it ?

Thanks for your help :)

**Comment by dicato** [comment]
@maxcanada I think it's safe to say those questions can be turned into issue on the allauth-2fa project! Feel free to open an issue there!  https://github.com/percipient/django-allauth-2fa

**Comment by maxcanada** [comment]
Will do, thanks!
