### ISSUE TITLE
Registration complete page incorrect when using the "simple" backend

### ISSUE THREAD

**Issue by allo-** [macropin/django-registration#187]
With the `simple` backend method, there is no confirmation e-mail, but the user is redirected to a page saying he should check his e-mails.

**Comment by yakupadakli** [comment]
https://github.com/macropin/django-registration/pull/239

**Comment by allo-** [comment]
Looks good. I think the option where to redirect should be added to documentation, then the bug can be closed.

**Comment by joshblum** [comment]
closed by #239
