### ISSUE TITLE
Compile locales in setup.py

### ISSUE THREAD

**Issue by allo-** [macropin/django-registration#188]
You can use this snippet in ``setup.py`` to compile locales while installing:

    class install_lib(_install_lib):
        def run(self):
            from django.core.management.commands.compilemessages \
                import compile_messages
            os.chdir('registration')
            compile_messages(sys.stderr)
            os.chdir("..")

**Comment by dicato** [comment]
@allo- are you interested in making this improvement into a pull request?

**Comment by allo-** [comment]
Seems like some stuff changed, so there are two ways to compile the locales.
I am not sure if ``handle`` is the most elegant way, but it seems otherwise we need to implement code searching for the relevant files, like ``handles`` does.

**Comment by allo-** [comment]
Updating this in another project for django 1.7+, i get 

    django.core.management.base.CommandError: This script should be run from the Django Git checkout or your project or app tree, or with the settings module specified.

while it works in the django-registration virtualenv in the top folder of the source (without any django project created). Please check if this works for you as well or if you get with this commit similiar problems while building (bdist) or installing.

**Comment by allo-** [comment]
Oh, it works for django 1.9 but is broken for 1.8. They seem to change this part quite often.

**Comment by allo-** [comment]
If it's not to late, can you replace the commit with https://github.com/macropin/django-registration/commit/df4a36b22126736872e5a269d0514ec541917db5?
It does not only have a more concise commit message, but i also fixed my real name in the author field, which wasn't set.
