### ISSUE TITLE
django-registration: cleanup task deletes users?

### ISSUE THREAD

**Issue by ThomasWaldmann** [macropin/django-registration#196]
Does this also affect django-registration-redux?

https://twitter.com/ubernostrum/status/744789922280681473

**Comment by dicato** [comment]
Here is the current code: https://github.com/macropin/django-registration/blob/fb8f7b68290cc4f90e2a97acf7346d381f0f3542/registration/models.py#L161

No, this does not affect this package.

**Comment by ThomasWaldmann** [comment]
Thanks for the clarification!

**Comment by dicato** [comment]
My pleasure. ubernostrum's package deviates quite a bit from the original django-registration (now django-registration-redux; confusing right? :smile:)
