### ISSUE TITLE
update copyright ownership

### ISSUE THREAD

**Issue by dicato** [macropin/django-registration#198]
@macropin any idea what the copyright should be?

**Comment by macropin** [comment]
I don't think this should have been merged. 

I believe something such as the following would be appropriate given that we do not force contributors to assign copyright:

```
Copyright (c) 2007-2013, James Bennett
Copyright (c) 2014-2016, Andrew Cutler, Stephen DiCato
 and others (see AUTHORS)
```

**Comment by dicato** [comment]
@macropin I'll open a PR right now.

I merged it because I, potentially erroneously, assumed the current year was better than last year. My apologies.
