### ISSUE TITLE
Allow squash merging on master

### ISSUE THREAD

**Issue by joshblum** [macropin/django-registration#200]
I think this feature is useful for landing large features to keep the git history clean

![screen shot 2016-07-05 at 12 09 19](https://cloud.githubusercontent.com/assets/1144020/16591311/533760e6-42a9-11e6-8756-8da58c8bd9b2.png)

**Comment by dicato** [comment]
@joshblum what's your thought on rebasing prior to merging? It puts the task on the submitter, for better or worse.

**Comment by joshblum** [comment]
I think GitHub allows you to click "update branch" and then you can merge
the rebased version

**Comment by joshblum** [comment]
Also protecting the master branch is a good idea (on the same settings area)

**Comment by timgraham** [comment]
We do squash merging on Django itself. For any pull requests that do use multiple commits and don't want squashing, we merge those [using the command line](https://docs.djangoproject.com/en/dev/internals/contributing/committing-code/#handling-pull-requests).

**Comment by dicato** [comment]
👍 @macropin will have to configure this.

**Comment by macropin** [comment]
It's already enabled.

**Comment by joshblum** [comment]
Oh, can we disable merge commits then?
