### ISSUE TITLE
django-registration + ajax

### ISSUE THREAD

**Issue by megavenik** [macropin/django-registration#208]
Hello!

Is there a way to register/login users with this module via ajax? I've looked for the information about it in docs and google, but found nothing unfortunately(

Thanks a lot!

**Comment by dicato** [comment]
No, django-registration does not support this. However, Django does have [JsonResponse objects](https://docs.djangoproject.com/en/1.10/ref/request-response/#jsonresponse-objects) and there are a variety or other projects out there integrating Django with AJAX, Angular, and many other popular front end technologies and frameworks.

* here is a [wiki page](https://code.djangoproject.com/wiki/AJAX) on Django and AJAX 
* the popular [django-angular](https://github.com/jrief/django-angular)

I'm going to close this issue, but feel free to ask more questions.

**Comment by megavenik** [comment]
Oh, I think, we have a small misunderstanding here. Sorry for not quite plain description of my situation.

Let me add more details. I'm not looking for an app that will help me add ajax-requests to django. I'm already using angular. And when I've tried to add user-pass registration to my project, using django-registration, I've discovered that all forms and methods accept POST requests with returning the whole page or redirect as a result.

As you can assume, it's a little bit hard to create an ajax-based registration form, when backend returns whole pages, not JSON-objects.

So, here is my question - is there a way to force django-registration to return JSON-objects to use then via ajax or not?

Thanks a lot for your patience!

**Comment by dicato** [comment]
> So, here is my question - is there a way to force django-registration to return JSON-objects to use then via ajax or not?

No.

However, you can write your own custom views that inherit from code in django-registration that pass JSON objects back instead of rendered HTML.

**Comment by megavenik** [comment]
Ok, I see, thanks!

**Comment by kovaacs** [comment]
@megavenik did you end up doing so? I'm in the same boat

**Comment by megavenik** [comment]
@kovaacs hi! I end up writing my own view on register and log in users with login/password pairs:) Without this module. After all, it wasn't a big deal - just look into some articles like this https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html

**Comment by kovaacs** [comment]
@megavenik I couldn't find a purely AJAX way. I feel that using forms is very lazy and adds code for no reason. I ended up rewriting this module's backend to support AJAX. When I have time I'll make it compatible with the current release it submit a PR.
