### ISSUE TITLE
Redirect after activation complete. 

### ISSUE THREAD

**Issue by jholms** [macropin/django-registration#211]
I was wondering if there is an easy way to redirect to the login page after successful activation. I tried to override the ActivationView with no success. 

class MyActivationView(ActivationView):
    def get_success_url(self, user):
        return 'registration/login.html'

url(r'^accounts/activate/complete$',ActivationView.as_view(),name='registration_activate'),

The register one worked fine, It is just this activation that is giving me a hard time.

**Comment by jholms** [comment]
Any update on this? Would be appreciated.

**Comment by dicato** [comment]
@jholms your approach looks correct. I suspect you forgot to import your custom view in your `urls.py` and update the url to use `MyActivationView` instead of the default.

**Comment by dicato** [comment]
@jholms did you get this fixed? I'm going to close the issue since no action is required on the part of the package maintainers but feel free to continue the conversation.
