### ISSUE TITLE
Documentation needed: overriding templates

### ISSUE THREAD

**Issue by alzearafat** [macropin/django-registration#212]
Hi there!

How I can override the default templates? Where I should put it?

Great plugin btw!

Thank you in advance for any help you can provide

**Comment by dicato** [comment]
You need to place your custom templates inside your template directory under a `registration` directory. For example, `registration/activation_email_subject.txt`. You can override any of the templates found in this directory:

https://github.com/macropin/django-registration/tree/master/registration/templates/registration

I thought this was documented, but apparently not!

**Comment by alzearafat** [comment]
Hi @dicato , thank you for fast response!

I found a way to solve my issue, I don't know if it's the best way or not (Maybe you can confirm this?), but at least it works for me.

I made new directory called `templates` inside my app, and add this setting is `settings.py`: 

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["app_guide/templates"], # Copy and paste all registration directory, to this directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

And then I just copy and paste registration directory, to app_guide/templates. So I can override it.
