### ISSUE TITLE
create_new_activation_key is insecure

### ISSUE THREAD

**Issue by keattang** [macropin/django-registration#213]
It uses the python `random.random` which is not cryptographically secure and also unnecessarily uses the user's ID in the hash which makes it possible (although improbable) for the same key to be generated for a different user if their IDs overlap. For example, a user is created with an ID, then at some point deleted and a new user is created with the same ID.

I suggest using an algorithm that uses a secure random function to create an entirely random string or at least allow the user to specify their own algorithm.

Such an algorithm may look like this:

```
def create_new_activation_key(self, save=True):
        """
        Create a new activation key for the user
        """
        self.activation_key = hashlib.sha1(os.urandom(32)).hexdigest()
        if save:
            self.save()
        return self.activation_key
```

I am happy to make a PR if this is something you will consider merging?

**Comment by dicato** [comment]
We would be happy to accept a pull request to address this issue!

Changing `random.random` to `os.urandom` is a good approach! I don't see any reason why this change would have backwards incompatible side effects, but please think through that as well. Thanks!
