### ISSUE TITLE
settings REGISTRATION_EMAIL_HTML  to reset password mail too

### ISSUE THREAD

**Issue by CleitonDeLima** [macropin/django-registration#217]
My solution to send email in html:

```python
url(r'^accounts/password/reset/$',
        auth_views.password_reset,
        {
            'post_reset_redirect': reverse_lazy('auth_password_reset_done'),
            'html_email_template_name': 'registration/password_reset_email.html'
        },
        name='auth_password_reset'),
```

Today there is a better solution?

**Comment by dicato** [comment]
That's probably the best way to do it at the moment. Please remember that password reset is provided by Django in `django.contrib.auth.views` and the URLs are imported as `auth_urls` in this package: https://github.com/macropin/django-registration/blob/master/registration/auth_urls.py
