### ISSUE TITLE
Assumption that user models have 'username' field

### ISSUE THREAD

**Issue by dpoirier** [macropin/django-registration#22]
There's a built-in assumption that all user models have a field named `username` .  If django-registration-redux instead looked at `get_user_model().USERNAME_FIELD`, it would handle custom user models better, I think.

**Comment by michellemark** [comment]
I agree, I am now trying to figure out how the author intended for a custom user with email as the USERNAME_FIELD to work.  If it can be done this is not obvious, and I could use an example.

**Comment by dpoirier** [comment]
I looked at it a little more yesterday and concluded it probably wasn't that simple.

**Comment by michellemark** [comment]
I think this might be the reason I switch... you might want to check out django-user-accounts https://django-user-accounts.readthedocs.org/en/latest/

**Comment by michellemark** [comment]
Or I just found this beautifully simple option as well https://github.com/mfogel/django-simple-email-confirmation

**Comment by macropin** [comment]
@dpoirier happy to accept a patch here. Looks like an omission as the support for custom user models is new and not well tested.

**Comment by pahaz** [comment]
https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#specifying-a-custom-user-model

**Comment by rollokb** [comment]
What exactly would be so hard about using the `USERNAME_FIELD` instead of `username`?

**Comment by martey** [comment]
The initial issue described here (using `USERNAME_FIELD` instead of `username`) should be fixed by #24.

**Comment by macropin** [comment]
Closing as @martey has indicated #24 resolved this.
