### ISSUE TITLE
Error include is not defined

### ISSUE THREAD

**Issue by Jakub41** [macropin/django-registration#220]
Hello,
when I'm trying to setup the registration I'm getting an error here:
(r'^accounts/', include('registration.backends.default.urls')),
Undefined reference include.
I have no idea why of that.
Can you help me please?
I'm using Pycharm and under my packages redux is installed.
Thank you

**Comment by joshblum** [comment]
Hey @Jakub41 it sounds like you didn't import the `include` function in your file. Try adding this line to the top of file:

`from django.conf.urls import include`

Let me know if you have any other issues!

**Comment by Jakub41** [comment]
Hey @joshblum  I will try your suggestion and back to you.
Thank you :)

**Comment by Jakub41** [comment]
Hi @joshblum I resolved the problem thank you :)

**Comment by joshblum** [comment]
@Jakub41 no problem!
