### ISSUE TITLE
Integration with django post office

### ISSUE THREAD

**Issue by felixSchl** [macropin/django-registration#225]
Am I correct in assuming I'd have to fork and modify [models.py](https://github.com/macropin/django-registration/blob/5fdd9882e5a2bfb1249d8c16d8c6f771e2434a4d/registration/models.py#L26-L55) by hand or is there an less intrusive way to integrate with [django-post-office](https://github.com/ui/django-post_office)?

**Comment by dicato** [comment]
@felixSchl Unfortunately I don't have any first hand experience. What does integrating with django-post-office entail?

**Comment by felixSchl** [comment]
Essentially we'd need a way to override how mail is sent. This could be done either by letting the user bring a function or by adding direct support. I think the former would enable, but not  require the latter and is therefore preferred imo.

**Comment by felixSchl** [comment]
It would probably be enough to somehow be able to alter the execution of this part of `send_email`: https://github.com/macropin/django-registration/blob/5fdd9882e5a2bfb1249d8c16d8c6f771e2434a4d/registration/models.py#L43-L55.

Here's an example from the post office docs on how to send email using post office:

```
from post_office import mail

mail.send(
    ['recipient1@example.com'],
    'from@example.com',
    subject='Welcome!',
    message='Welcome home, {{ name }}!',
    html_message='Welcome home, <b>{{ name }}</b>!',
    headers={'Reply-to': 'reply@example.com'},
    context={'name': 'Alice'},
)
```

I think it should pretty much be plug and play once we sort out a way to let users bring their own function / choose a backend, or something like that.

**Comment by dicato** [comment]
Interesting. This seems more appropriate to discuss on django-post-office. Does the project hook into [Django's email backends](https://docs.djangoproject.com/en/1.10/topics/email/#email-backends)?

**Comment by felixSchl** [comment]
Sorry, there must have been a misunderstanding on my end because as you said it does integrate and choosing it as a backend does queue the e-mail as it should. I just tried it out and it all works magically. I must have got led astray by the rest of the docs doing `post_office` imports. Thank you for pointing this out to me :)

**Comment by dicato** [comment]
😄 My pleasure! I'm happy you figured it out.
