### ISSUE TITLE
New release (1.5?)

### ISSUE THREAD

**Issue by felixSchl** [macropin/django-registration#226]
I am wondering when you are planning on releasing the next version that includes the 3 step registration flow? The feature seems to have been in the code-base for quite some time now (~5 months), so I figured I'd ask here.

**Comment by dicato** [comment]
Yes, we absolutely should. #206 needs to be addresses first. That's the only issue I see as a holdup.

**Comment by Fingel** [comment]
Django 1.11 is out and is now incompatible with django-registration-redux. This was fixed in https://github.com/macropin/django-registration/pull/194

**Comment by joshblum** [comment]
@Fingel we're working on a release and it will be on pypi soon!

**Comment by joshblum** [comment]
Just released! https://pypi.python.org/pypi/django-registration-redux/1.5

**Comment by Fingel** [comment]
@joshblum Congrats! Thanks for the great work.
