### ISSUE TITLE
Jinja2 error during rendering email rendering

### ISSUE THREAD

**Issue by G-Nick** [macropin/django-registration#227]
Hi. I'm using Jinja2 template backend and I've got next error in send_activation_email method of RegistrationProfile model in registration/models.py in this line.

```
subject = (getattr(settings, 'REGISTRATION_EMAIL_SUBJECT_PREFIX', '') +
                   render_to_string(
                       activation_email_subject, ctx_dict)) 
```

```
ValueError at /signup/
dictionary update sequence element #0 has length 4; 2 is required
```

After looking through the stack trace I think the error occurs because of using RequestContext instead of passing request object inside render function. I've also found that this change is actually in the codebase, but current release (1.4) doesn't have it. Not sure what should I do in this case.

**Comment by dicato** [comment]
@G-Nick this project is clearly in need of a new release. There is not much to see but we are tracking the release in this issue and have one blocker that needs to get addressed prior - https://github.com/macropin/django-registration/issues/226.

It's a workaround, but you can install directly from source if you so desire. For example, if you want to install the latest commit on master, you can run: `pip install https://codeload.github.com/macropin/django-registration/zip/5fdd9882e5a2bfb1249d8c16d8c6f771e2434a4d`.

Note, it's a complete workaround you shouldn't have to do.
