### ISSUE TITLE
The right way to know if the profile is expired is to look at date_joined?

### ISSUE THREAD

**Issue by xicopetry** [macropin/django-registration#232]
Hello!
First I'll like to thank you guys for the support for this really helpful app!

So, my question is this:
Lets say if a user that already have a Login go to my site and he decides to change his email. So, in my point of view, it is needed to resend an activation email again, to verify if this email is valid.
So, I set the user to inactive (user.is_active=False) and call the resend_activation_mail.
The user will go to his inbox, click on the link that I sent and activate his user again.

This workflow seems coherent, right?
But is not. If you see the code for the activate_user it only active a user that is not expired. And to know if the RegistrationProfile is expired it looks based on the date_joined field, that can be months ago! So that user will no longer be able to active his profile.

An other problem that I see that can happen is, If Model User have the email field defined as unique=True and the user don't have a login yet:
The user fill his profile to create a new profile with a email that he is not the owner, so, the user will never be activate.

If another user try to create a profile with this same email it won't be able.
So a user can disable a email forever, even if the user is not the owner of the email address.

----------------------------------------------------------------------------------------------------
What are your suggestions to resolve this?
Maybe could have a field in the RegistrationProfile, like date_created. And the is_expired method look for this field instead of the date_joined of the user.
I will be thankful to help!

**Comment by dicato** [comment]
@xicopetry good questions. :smile:

If you allow a user with a verified email to change their email, the common workflow is to verify the new email address but not necessarily make the user account inactive. This might not make sense for your application.

django-registration doesn't have any capabilities to help with email management and does not intend to. If you are looking for a more comprehensive Django package that helps manage users, handle authentication, and still solves the registration use cases I would highly suggest [django-allauth](https://github.com/pennersr/django-allauth).
