### ISSUE TITLE
Log accounts being deleted in routine cleanup task

### ISSUE THREAD

**Issue by felixSchl** [macropin/django-registration#233]
We just lost about 10 valid accounts and are in the process of recovering them, unfortunately at this point I am guessing that it must have been django-registration's clean up task but there's no way of knowing for sure, the data is just gone. If it logged the accounts to be deleted before actual deletion, I could go back to be cron job's log file and check what happened and when.

**Comment by dicato** [comment]
Are you calling the `cleanupregistration` management command via cron?

Looking at the [tests](https://github.com/macropin/django-registration/blob/37a881cdf11eb38e96a5b830201e238f96151936/registration/tests/models.py#L349) for the [delete_expired_users](https://github.com/macropin/django-registration/blob/37a881cdf11eb38e96a5b830201e238f96151936/registration/models.py#L201) method, it certainly could be improved.

Have you tried to recreate this issue? Can you?

**Comment by felixSchl** [comment]
Yes, calling it via cron and piping the output to a file, but there's no output.

I'd say the core issue here is the lack of overview of what's happening. If it was django registration, the only thing I can think of are timezone issues or something like that. I will spend time looking into this further after I recovered the accounts properly.

**Comment by dicato** [comment]
@felixSchl I can appreciate the frustration here and desire to figure out the problem. The lack of comprehensive tests for this is disappointing and something that should clearly be fixed.

**Comment by felixSchl** [comment]
I just noticed something else, i think [this](https://github.com/macropin/django-registration/blob/master/registration/models.py#L243) should read:

```
 if profile.activation_key_expired() and not profile.activated:
```

**Comment by dicato** [comment]
@felixSchl you are probably right regarding that condition, since it's clearer. However the logic currently uses `if not user.is_active:` so it doesn't seem like a bug.

**Comment by felixSchl** [comment]
But `user.is_active` is something that could change irrespective of initial successful registration, right? For example when temporarily suspending an account.

**Comment by dicato** [comment]
Great point! Yes, I can absolutely see that use case causing inactive accounts being deleted erroneously.

We should:

1) fix the logic to use `if profile.activation_key_expired() and not profile.activated:`
2) add/improve the unit tests for this
3) add logging to the management command that uses this code

**Comment by joshblum** [comment]
@felixSchl are you able to submit a patch to fix this?
