### ISSUE TITLE
Username case insensitive check

### ISSUE THREAD

**Issue by pando85** [macropin/django-registration#234]
I read that this feature was implemented in v0.5 but I'm testing v1.4 with Django 1.10 and It isn't working.
Any ideas?

**Comment by pando85** [comment]
Could #235 help?

**Comment by joshblum** [comment]
@pando85 is the functionality you're describing implemented in #250 ?

**Comment by pando85** [comment]
@joshblum  No, I understand that's only make email case insensitive when recovering password.

I want a Django model user case insensitive.

I don't like `iexact` filter because it adds a lot complexity and queries can be very slow in big databases. 

My solution was make username to lower case and I think email must do the same.

**Comment by joshblum** [comment]
closed by #251
