### ISSUE TITLE
Default ActivationView doesn't check whether user is already activated

### ISSUE THREAD

**Issue by delano** [macropin/django-registration#240]
In the [default ActivationView](https://github.com/macropin/django-registration/blob/v1.4/registration/backends/default/views.py#L119-L138), the call to `RegistrationProfile.activate_user` returns the `User` object when the user is first activated but also if the user is already activated. So in the view, there's no way for it to know whether it's the initial activation. 

```python
class ActivationView(BaseActivationView):
    def activate(self, *args, **kwargs):
        activation_key = kwargs.get('activation_key', '')
        activated_user = (RegistrationProfile.objects
                          .activate_user(activation_key))
        if activated_user:
            signals.user_activated.send(sender=self.__class__,
                                        user=activated_user,
                                        request=self.request)
        return activated_user
```

This leads to two issues:
* The `user_activated` signal is called each time a user clicks an activation link. Say for example, if this signal is used to send a notification, that notification will get sent every time.
* If `REGISTRATION_AUTO_LOGIN` is set to `True`, the activation link can be used as a login link indefinitely. 

Note: [this is an issue in the original `django-registration` as well](https://github.com/ubernostrum/django-registration/blob/2.2/registration/views.py#L93-L113)

**Comment by dicato** [comment]
@delano thanks for filing this! Are you interested in trying to improve this?

I'll take a look through the code to refresh my memory before making any suggestions.

**Comment by delano** [comment]
@dicato Yeah I can push a fix, no problem. Maybe tomorrow but within the next week for sure.

**Comment by joshblum** [comment]
@delano are you still interested in working on this?

**Comment by delano** [comment]
Yeah sorry for the delay!

**Comment by delano** [comment]
@joshblum There are a couple options for this but nothing that doesn't change current expected functionality or isn't hacky. There is one option that isn't hacky but it requires a second hit to the DB. 

* Have `RegistrationManager.activate_user` return a tuple (e.g. `(profile_user, True)`). This would be similar to Django's `get_or_create` method but would require updating every call this this method (and would be a breaking change for end users that have custom registration views).
* Call the signal from within `RegistrationManager.activate_user` when `profile.activated` is false. Has side effects since this is called from places other than the view (and would need to pass is the `request` object).
* In `ActivationView.activate`, call the DB before `RegistrationManager.activate_user` to see if the profile was already activated.
* Delete the `RegistrationProfile` record when the user is activated or add `activated=False` to the query in `RegistrationManager.activate_user`. These will have the same side effects. 

It's not clear what the case is for passing back an already activated user. Ideally this wouldn't be necessary and if it isn't, then the last option is the best. If it is, then we'll need to decide which of the others to go for.

**Comment by joshblum** [comment]
@dicato do you have any preferences between these options?

**Comment by delano** [comment]
I don't have enough history with the project to give a definitive answer. It comes down to whether you are okay with a non-backwards compatible change to the current functionality. 

If no, the least invasive option is (C), a second hit to the DB. If yes, the best option is (A), return a tuple. Note: if you follow semver, this would trigger a major version increment (i.e. 2.0).

**Comment by joshblum** [comment]
@delano I'm also a newer contributor so don't know what option would be best, I'll defer to @dicato or @macropin

**Comment by delano** [comment]
@joshblum Sounds good. Thanks for following up before btw to keep this moving.

**Comment by dicato** [comment]
Hey, I'll try and take a look soon, most likely this weekend. I need to refresh my memory on why the current behavior is the way it is. :smile:

That said, I'm 100% in support of backwards incompatibility when the changes:

* provide useful functionality
* are easier to maintain
* are an obvious improvement

...so with that, if you feel strongly in favor of one of your options, please consider moving forward on it.
