### ISSUE TITLE
TemplateDoesNotExist at /accounts/login/ base.html

### ISSUE THREAD

**Issue by repodevs** [macropin/django-registration#241]
Hi, 
I tried install `django-registration-redux` with `django==1.10.4` & `python 3.5` but I got an error

![screenshot at 2017-03-24 11-03-45](https://cloud.githubusercontent.com/assets/13567128/24280286/f5c892f2-1081-11e7-8529-c9360249cb5b.png)

![screenshot at 2017-03-24 11-06-10](https://cloud.githubusercontent.com/assets/13567128/24280289/07da2730-1082-11e7-9a8e-5823d63a8917.png)

My configuration:
`settings.py`
```python
INSTALLED_APPS = [
    'django_adminlte',
    'django_adminlte_theme',
    'django.contrib.admin',
    'registration',
    'django.contrib.auth',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REGISTRATION_AUTO_LOGIN = True # Automatically log the user in.
SITE_ID = 1
LOGIN_REDIRECT_URL = '/dashboard'
```
`urls.py`
```python
urlpatterns = [
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/$', dashboard_views.dashboard, name='dashboard'),
]
```

any idea ?

**Comment by joshblum** [comment]
@repodevs I think you issue is that you don't have a `base.html` in your project. Checkout these docs: http://django-registration-redux.readthedocs.io/en/latest/quickstart.html#templates Will close for now but reopen if you're having issues :)
