### ISSUE TITLE
Can't find 1.5 on pypi

### ISSUE THREAD

**Issue by odinho** [macropin/django-registration#247]
It doesn't seem to work with Python 2.7:

```
$ pip install --upgrade django-registration-redux==1.5
Collecting django-registration-redux==1.5
  Could not find a version that satisfies the requirement django-registration-redux==1.5 (from versions: 1.1, 1.2, 1.3, 1.4)
No matching distribution found for django-registration-redux==1.5
```
Though the PyPi page says it will work with both 2 and 3: https://pypi.python.org/pypi/django-registration-redux

The only wheel which is there is the one for Py3 though, not a `py2.py3` package.

Could the package be updated to also allow Py2 if it works?

**Comment by dicato** [comment]
@odinho I just pushed a Python wheel for Python 2. Can you please let me know if installs work for you again?

Thanks!

**Comment by odinho** [comment]
@dicato Hi, it works now, thanks! :)

**Comment by dicato** [comment]
👍
