### ISSUE TITLE
Enable "enforces email uniqueness"

### ISSUE THREAD

**Issue by alzearafat** [macropin/django-registration#256]
Hi there!

The email is not unique by default, I can register multiple times with same email. How I can enable it? I cannot find the conf in the docs (or maybe I missed it?)

And how to login using email instead of username?

Any help would be greatly appreciated

Thank you!

**Comment by dicato** [comment]
> The email is not unique by default, I can register multiple times with same email. How I can enable it? I cannot find the conf in the docs (or maybe I missed it?)

You need to use the appropriate registration form - [see here](http://django-registration-redux.readthedocs.io/en/latest/forms.html#registration.forms.RegistrationFormUniqueEmail)

> And how to login using email instead of username?

django-registration-redux provides a set of utilities for registering users. It does not deal with authentication. You are going to either want to extend Django's authentication system manually or with an applicable package. For example, [django-allauth](http://django-allauth.readthedocs.io/en/latest/configuration.html) allows configurable authentication using username, email, or both.

**Comment by alzearafat** [comment]
Thanks @dicato !

**Comment by dicato** [comment]
@alzearafat if you think the docs can be improved, please don't hesitate to suggest some changes in a PR. 👍
