### ISSUE TITLE
Change look of forms

### ISSUE THREAD

**Issue by saadtaame** [macropin/django-registration#257]
Is there a way to change the look of registration forms ? Assign them CSS classes for example.

**Comment by joshblum** [comment]
@saadtaame you can override the templates that we provide and add classes as necessary: http://django-registration-redux.readthedocs.io/en/latest/quickstart.html. If you want to edit the look/feel of the forms themselves some other projects that might be helpful are: https://github.com/django-crispy-forms/django-crispy-forms or https://github.com/kmike/django-widget-tweaks
