### ISSUE TITLE
string index out of range

### ISSUE THREAD

**Issue by cucy** [macropin/django-registration#278]
```python
IndexError at /accounts/activate/6ffd9b5ef4ff55fd6fce85bf9df79b8b6b5f1e42/
string index out of range


  File "/home/xxx/.pyenv/versions/reg_user3.5.3/lib/python3.5/site-packages/registration/models.py", line 549, in <listcomp>
    admins = [admin[1] for admin in admins]
```

**Comment by joshblum** [comment]
@cucy I think that your `settings.py` file is improperly written. Here is an example of what the `ADMINS` list must look like: https://github.com/macropin/django-registration/blob/master/test_app/settings_test.py#L54

Let me know if this fixes your issue!

**Comment by joshblum** [comment]
@cucy was this issue resolved with the change to `settings.py`?

**Comment by joshblum** [comment]
The format of the setting is dictated by Django https://docs.djangoproject.com/en/1.11/ref/settings/#admins. I agree it would fix it in this case but think it's better to have the setting properly set for consistency/expectations of other code. @cucy I'm going to close this for now, let me know if you run into anything else!
