### ISSUE TITLE
Pass cleaned form data to user_registered signal handler

### ISSUE THREAD

**Issue by atleta** [macropin/django-registration#28]
If we use a custom form with backends.default.RegisterView (which should be possible according to the documentation, but can't actually be done as of now), cleaned form data should be passed to the signal handler to allow processing of extra fields.

I'm trying to upgrade from 0.8.0 where custom form (specifying it and handling its extra fields) could be handled by overriding the backend class. Now this may not be the right way to do it, but there is no easy way to achieve this (the only one seems to be subclassing RegisterView *and* providing my own urlconf).

**Comment by AMeng** [comment]
@atleta, are you still seeing an issue with custom form classes in `django-registration-redux==1.2c1`?

**Comment by macropin** [comment]
This is presumed fixed in v1.2.
