### ISSUE TITLE
Bug: url "registration_resend_activation" raises an exception if a several users registered with one email 

### ISSUE THREAD

**Issue by Kifsif** [macropin/django-registration#282]
**django-registration-redux==1.7**

I registered a new user. Then registered another user with the same email.
Registration went ok. And then registered a third user with the same email.
In the traceback you can see 3 that get() returned 3 in ExceptionValue.

Then I went to: 
http://localhost:8000/accounts/activate/resend/

Well, it rose an exception. This seems to be a bug.

`Environment:

Request Method: POST
Request URL: http://localhost:8000/accounts/activate/resend/

Django Version: 1.11.4
Python Version: 3.6.2
Installed Applications:
['django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'home',
 'reg',
 'registration',
 'django.contrib.admin',
 'django.contrib.auth',
 'crequest',
 'deployment',
 'general',
 'personalarea',
 'places',
 'people',
 'frames',
 'frameplaces',
 'frameplaceshistory',
 'framepeople',
 'framepeoplehistory',
 'framedates',
 'framedateshistory',
 'framewiki',
 'framewikihistory',
 'items',
 'itemwiki',
 'itemwikihistory',
 'sheets',
 'bookmarks',
 'files',
 'images',
 'notes',
 'noteshistory']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'crequest.middleware.CrequestMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/home/michael/PycharmProjects/venv/photoarchive/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/michael/PycharmProjects/venv/photoarchive/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/michael/PycharmProjects/venv/photoarchive/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/michael/PycharmProjects/venv/photoarchive/lib/python3.6/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/home/michael/PycharmProjects/venv/photoarchive/lib/python3.6/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/home/michael/PycharmProjects/venv/photoarchive/lib/python3.6/site-packages/django/views/generic/edit.py" in post
  183.             return self.form_valid(form)

File "/home/michael/PycharmProjects/venv/photoarchive/lib/python3.6/site-packages/registration/views.py" in form_valid
  124.         self.resend_activation(form)

File "/home/michael/PycharmProjects/venv/photoarchive/lib/python3.6/site-packages/registration/backends/default/views.py" in resend_activation
  167.             email, site, self.request)

File "/home/michael/PycharmProjects/venv/photoarchive/lib/python3.6/site-packages/registration/models.py" in resend_activation_mail
  187.             profile = self.get(user__email__iexact=email)

File "/home/michael/PycharmProjects/venv/photoarchive/lib/python3.6/site-packages/django/db/models/manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/home/michael/PycharmProjects/venv/photoarchive/lib/python3.6/site-packages/django/db/models/query.py" in get
  384.             (self.model._meta.object_name, num)

Exception Type: MultipleObjectsReturned at /accounts/activate/resend/
Exception Value: get() returned more than one RegistrationProfile -- it returned 3!
`

**Comment by joshblum** [comment]
@Kifsif thanks for reporting! There was a `TODO` left to catch this error that hasn't been implemented yet (https://github.com/macropin/django-registration/blob/master/registration/models.py#L190) @dicato what are your thoughts? We could return the first profile found (instead of a `.get`) but that might be odd behavior. @Kifsif open to your thoughts as well on how to fix the issue!

**Comment by Kifsif** [comment]
Is it possible to forbid the registration of multiple accounts with one email? I think, this is the only possible way to reliably handle activation. If the strategic line is to forbid multiple use of one email, maybe it is better to return the first profile. Some users may feel some inconvenience. I think there will be few such users. Almost painless.

**Comment by joshblum** [comment]
You can already enforce email uniqueness using the [`RegistrationFormUniqueEmail`](http://django-registration-redux.readthedocs.io/en/latest/forms.html#registration.forms.RegistrationFormUniqueEmail). With this the bug should not occur since no users with the same email cannot register. We will need something more general if this the `RegistrationFormUniqueEmail` is not used

**Comment by joshblum** [comment]
@Kifsif were you able to fix the probem with the `RegistrationFormUniqueEmail`? If so we can close this issue for now.

**Comment by Kifsif** [comment]
@joshblum, well, RegistrationFormUniqueEmail is a good variant. If this solves the issue, well, let's close it. Though such exceptions will continue in future for other people.
