### ISSUE TITLE
Templates blocktrans refactoring

### ISSUE THREAD

**Issue by LennyLip** [macropin/django-registration#29]
Blocktrans in templates
https://github.com/macropin/django-registration/tree/master/registration/templates/registration
does not support dict, list, etc. So this record

```
{{ site.name }}
```

in blocktrans is wrong and does not work.

it must be something like that

```
{% blocktrans with site_name=site.name %}
{{ site_name }} registration
{% endblocktrans %}
```

**Comment by macropin** [comment]
Please submit a patch.
