### ISSUE TITLE
el translation trivial fix

### ISSUE THREAD

**Issue by feroda** [macropin/django-registration#30]
Hello, using django-rosetta app to let users able to translate my own project,
I found this "bug" in your locale .po file for the "el" language.

~/.virtualenvs/gf-dj17/lib/python2.7/site-packages/registration/locale/el/LC_MESSAGES/django.po
LINE 68
"Η εγγραφή μέσω δωρεάν διευθύνσεων ηλεκτρονικού ταχυδρομείου απαγορεύεται. ""Παρακαλώ δώστε κάποια άλλη."                              

I don't know el language but I think that line should just break between the two "" so my patch :) is :+1: 

"Η εγγραφή μέσω δωρεάν διευθύνσεων ηλεκτρονικού ταχυδρομείου απαγορεύεται. "
"Παρακαλώ δώστε κάποια άλλη."

**Comment by macropin** [comment]
Can you please submit this as a pull request. Thanks
