### ISSUE TITLE
Duplicate url pattern name

### ISSUE THREAD

**Issue by erikcw** [macropin/django-registration#306]
The name `auth_password_reset_done` is listed for two different url patterns in [auth_urls.py](https://github.com/macropin/django-registration/blob/master/registration/auth_urls.py#L49)

It is being used for both `r'^password/reset/$'` and `r'^password/reset/done/$'`.  The former should be changed to just `auth_password_reset`

**Comment by joshblum** [comment]
@erikcw the naming is correct as far as I can see, the `password/reset/` view has a `success_url` parameter which points to `auth_password_reset_done`. Closing this for now, let me know if you run into any issues.

**Comment by erikcw** [comment]
You're right, my mistake.  Eyes are playing tricks on me...
