### ISSUE TITLE
reverse_lazy() should take a view function name as input instead of a string

### ISSUE THREAD

**Issue by zhuyuecai** [macropin/django-registration#316]
since in urls.py, all reverse_lazy() for the success url are passed by a string(the url name), it raise no page found when for example I reset my password before log in. it should redirect to a the url 
^accounts/ ^password/reset/done/$ [name='auth_password_reset_done']
however, the url actually redirecting is : 
/accounts/password/change/auth_password_change_done 

should change reverse_lazy() to redirect() with the same input?

**Comment by joshblum** [comment]
@zhuyuecai I'm not sure I follow. Right now resetting your password has a [success url](https://github.com/macropin/django-registration/blob/master/registration/auth_urls.py#L47) of `auth_password_reset_done` and changing your password has a [success url](https://github.com/macropin/django-registration/blob/master/registration/auth_urls.py#L40) of `auth_password_change_done`.

**Comment by zhuyuecai** [comment]
Sorry, I make a mistake, I bug is in another django-registration, not this one, I will close the issue, I didn't know there is two django-registration .

**Comment by joshblum** [comment]
No problem!
