### ISSUE TITLE
using AbstractBaseUser

### ISSUE THREAD

**Issue by fumeno** [macropin/django-registration#317]
Hello All,

Now I'm trying to use django-registration with customize user.( AbstractBaseUser)
I changed USERNAME_FIELD. (username -> email)

Then I got a error on registration/models.py which said that user doesn't have username.
I checked models.py.  The following code use 'username', but I think it's better to use "get_username()'. Would you please consider this ?

------------Original--------------
  ctx_dict = {
           'user': self.user.username,
            'site': site,
        }
------------Original--------------
------------my opinion--------------
  ctx_dict = {
            'user': self.user.get_username(),
            'site': site,
        }
------------my opinion--------------

**Comment by joshblum** [comment]
@fumeno sorry about the issue! I think https://github.com/macropin/django-registration/pull/318 addresses your problem, take a look and let me know!

**Comment by fumeno** [comment]
@joshblum yes. that I would like to.

**Comment by joshblum** [comment]
Great! Closed by #318
