### ISSUE TITLE
Adding registration form on multipe pages

### ISSUE THREAD

**Issue by ShaunGuarini** [macropin/django-registration#32]
I want to add the registration form to my home page but also have it on the normal accounts/register. I couldn't find anything online, any help or direction appreciated.

**Comment by LennyLip** [comment]
This is not django-registration issue, i think you should use StackOverflow for such question.
In all, if you want registration form on a home page, you must send registrationFrom object to the template.

see RegistrationView in a registration\views.py

yoo'll see RegistrationForm there. 
1. you must create empty form like a "registraionForm = new RegistrationForm()" 
2 . and return it in a home view like a
return render(request, 'base/home.html', {'regform': registraionForm})
3. than you must set POST form  in a home template with action to {% url 'registration_register' %} and add registraionForm into it.

**Comment by macropin** [comment]
Please try a site such as StackOverflow
