### ISSUE TITLE
base.html

### ISSUE THREAD

**Issue by jackmullen2** [macropin/django-registration#34]
demo form registration_base_.html  extends base.html .. which does not exist ..  Is that an oversight or something expected to be written by user ?

**Comment by jeroenpeters1986** [comment]
Confirmed, I have the same thing. Also looked at the docs, but those hold no solutions

**Comment by macropin** [comment]
This is one of the issues of bundling templates with the project... assumptions need to be made. I think it's fairly common for projects to have a _base.html_ from which all other templates inherit. The PyPi package does not bundle the templates. They are only available here as a convenience #11. 

I would like to see them included in the future provided that the documentation is updated, and issues such as the above can be avoided.

**Comment by jeroenpeters1986** [comment]
Hi macropin, you are right! Now I know that base.HTML isn't a missing file in this repo but an assumption in a users project, I also recommend just to clarify the documentation (or a comment in registration_base.HTML) and leave it at that.
Sorry for taking up tour time and thank you for answering.

**Comment by derek-adair** [comment]
change it to registration_base.html and call it a day.  Again, as per my comments in #11, its about usability.  Its about lowering the barrier for entry in this plugin.  I work very well with working examples and often find I read instructions wrong.

Easily the biggest barrier of entry for me was installing this plugin and thinking, 'wtf, it doesn't just... work?'

This plugin should just... work.

Again, i can own #11 as well as this one if it will help you.

**Comment by macropin** [comment]
Yeap, I'll go with that. Let's call it `registration_base.html`. @derek-adair can you please own #11 and submit a PR for the template change. Thanks.

**Comment by derek-adair** [comment]
Sure thing, i am planning on setting up a site that requires registration.  I can have that on your desk some time next week i think ;)
