### ISSUE TITLE
Admins from database instead of settings

### ISSUE THREAD

**Issue by GasparPizarro** [macropin/django-registration#341]
It would be nice that the registration admins list could be pulled from the user model database instead of from the `settings py`. The use case for this is that the admin of an app (who would be different from the developer of the app) could add users for the registration approval without touching source code or having to enter the host machine. My proposal is that the registration admins would be the users with `is_superuser=True`, and if there are no users matching the criterion, the regular (`REGISTRATION_ADMINS or ADMINS`).

Thoughts on this?

**Comment by GasparPizarro** [comment]
Yes I am, give me some time to develop it and make a pull request.

**Comment by joshblum** [comment]
thanks!
