### ISSUE TITLE
Overriding templates not working

### ISSUE THREAD

**Issue by rossifumi46** [macropin/django-registration#357]
in settings 'APP_DIRS': True, but templates in myapp/templates/registration folder not overriding deafults.

**Comment by joshblum** [comment]
@rossifumi46 this is likely an issue with your directory structure/other django settings, can you provide any more debug info? does your setup match the examples here https://docs.djangoproject.com/en/2.1/howto/overriding-templates/?

**Comment by macropin** [comment]
Closing for now. Please feel free to reopen with more information.
