### ISSUE TITLE
When using Jinja, request user is preferred over ctx_dict's user

### ISSUE THREAD

**Issue by gone** [macropin/django-registration#365]
I'm seeing emails rendered with the request.user, which is still anonymous over the ctx_dict['user'] which is the new user. It looks to me like the request attributes are shadowing the context dictionary when they have a name collision?

**Comment by joshblum** [comment]
what version of the library and django are you using? Could you provide an example template where this happens?

**Comment by macropin** [comment]
Closing for now. Please feel free to reopen with more information.
