### ISSUE TITLE
In send_activation_email() if email_message.send() fails it creates user anyway

### ISSUE THREAD

**Issue by easternsun** [macropin/django-registration#366]
In the RegistrationProfile model, in the send_activation_email() method if an email fails to send for some reason (e.g. 400 bad request), the user is created anyway beforehand. Perhaps a try/except to delete the already created user and return an error message for the form if this happens?

**Comment by joshblum** [comment]
@easternsun what version of the library are you using? I think this is fixed in version 2.6 via https://github.com/macropin/django-registration/pull/355

**Comment by easternsun** [comment]
Apologies for the late reply. You are indeed correct, I was using version 2.5. Thanks.
