### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by BlueMonday** [macropin/django-registration#37]
I was wondering if we could get a new release (1.2)?

**Comment by macropin** [comment]
Agreed, but unfortunately I have no time to QA a release. Are you up for the task? I think we need a decision on #11 / #34. And there are a few other open issues regarding documentation (bugs), so the docs require a going over and update where required.

**Comment by skolsuper** [comment]
+1, I was surprised when the pip package didn't have the templates I could see in the github repo. Also, the readthedocs documentation is out of step too, as it only mentions a subset of the templates that users will actually need to implement to get the app working: 

http://django-registration-redux.readthedocs.org/en/latest/quickstart.html#required-templates

**Comment by derek-adair** [comment]
I am supposed to commit those changes in #11, i've been busy catching up with life though, very sorry.  I have a long flight on sunday where i can most certainly stub something out and submit a PR asap for the templates.

**Comment by skolsuper** [comment]
No need to apologise! I just had a read through there and #34, my 2 cents for what they're worth is that almost every project should have a base.html.  In fact I would argue for that to be in either the django-admin startproject or at least the djangoproject.com tutorial, it would be nice to have it as an accepted convention.

**Comment by skolsuper** [comment]
To clarify, I mean I agree with [this comment](https://github.com/macropin/django-registration/issues/34#issuecomment-78402507) on leaving it as is and just adding documentation.

**Comment by derek-adair** [comment]
Ya, thats a good point.  I misread #34 and confused it as the same issue as #11, i THINK i see what you mean.

It sounds like you propose the templates *should be* included and extend base.html, but base.html should not be, as it is a natural assumption for any django project.  correct?

**Comment by skolsuper** [comment]
Yes that's right.  Mainly because I use other packages (e.g. https://github.com/hovel/pybbm) that assume/require a base.html template so I already have it (i.e. laziness reasons), but I do think it's a useful pattern to encourage.

**Comment by derek-adair** [comment]
Yup, you've sold me.  My vote is now update the docs and encourage this de facto base.html pattern.

**Comment by skolsuper** [comment]
:thumbsup:

**Comment by AMeng** [comment]
I believe https://github.com/macropin/django-registration/issues/11 and https://github.com/macropin/django-registration/issues/22 are already fixed and should both be closed.

I've provided fixes for a few outstanding issues:
https://github.com/macropin/django-registration/pull/52 fixes https://github.com/macropin/django-registration/issues/34.
https://github.com/macropin/django-registration/pull/53 fixes https://github.com/macropin/django-registration/issues/12.
https://github.com/macropin/django-registration/pull/54 fixes https://github.com/macropin/django-registration/issues/17.

Let me know if there is anything else I can do to help make a 1.2 release happen.

**Comment by macropin** [comment]
Thanks @AMeng for your PR's. I've addressed #25. This release now needs testing. I've pushed an rc to pypi `pip install django-registration-redux==1.2c0`

**Comment by macropin** [comment]
Waiting to close off #27 before shipping this release.

**Comment by AMeng** [comment]
@macropin, how do you feel about a formal release or another RC?

**Comment by macropin** [comment]
@AMeng you seem to be all over the current issues ;). If you're happy. I'll push another rc now.

**Comment by macropin** [comment]
It's on PyPi now `pip install django-registration-redux==1.2c1`

**Comment by AMeng** [comment]
@macropin `1.2c1` is looking good from testing in my applications.

The current state of open issues (other than enhancements):
https://github.com/macropin/django-registration/issues/28 - No response, assumed fixed in 1.2c1
https://github.com/macropin/django-registration/issues/45 - No response, assumed fixed in 1.2c1
https://github.com/macropin/django-registration/issues/50 - Issue outside of this application. Should be closed.
https://github.com/macropin/django-registration/issues/39 - PR https://github.com/macropin/django-registration/pull/56 is open to fix this in the next release

Looks ready for an official release. :beers:

**Comment by macropin** [comment]
Thanks @AMeng for summarising this. 
Release pushed to PyPi https://pypi.python.org/pypi/django-registration-redux/1.2 Now to work on 1.3

**Comment by macropin** [comment]
v1.3 release has been made to PyPi. Thanks to all those that helped.
