### ISSUE TITLE
[question] how to change default location of registration folder

### ISSUE THREAD

**Issue by guanicoe** [macropin/django-registration#383]
Hi, 

I guess this is a simple question, but i cannot find it clearly in the docs. How do I change the default location of the registration folder without having to rewrite all the urls calls in urls.py?
Is there a variable I can set in settings?

Thanks

**Comment by joshblum** [comment]
@guanicoe you can change the `TEMPLATES` setting to point to a different directory of the same name so your templates are found first: https://docs.djangoproject.com/en/3.0/howto/overriding-templates/#overriding-from-the-project-s-templates-directory
