### ISSUE TITLE
Unnecessary mess with class-based view prototypes

### ISSUE THREAD

**Issue by Zopieux** [macropin/django-registration#39]
The [current views.py](https://github.com/macropin/django-registration/blob/62e115cf4ee21c49eb0097060839be55f48b0ba8/registration/views.py#L26) overrides many methods from Django `View` to "*pass the HTTP request nearly everywhere, to enable finer-grained processing*". Thing is, `request` is already available everywhere using `self.request`. As a result, when subclassing `RegisterView`, we have to deal with these weird prototype changes and code becomes messy.

What is the rationale for this? Would that be OK if I create a PR where I remove these (unecessary, AFAICT) overrides?

**Comment by macropin** [comment]
That's some code from James' original refactor for Django 1.5. As long as it doesn't break the tests, and backwards compatibility I'm happy to accept a PR. From a cursory glance, it looks like it might just be one of those "designed in isolation type" type things that you sometimes find. I find them from time to time in my old code. Usually written on a day when I ran out of coffee. :)

**Comment by Zopieux** [comment]
Fine, I'll try to find some time to change that and see if tests pass.

**Comment by AMeng** [comment]
@Zopieux, I opened a PR to hopefully fix this: https://github.com/macropin/django-registration/pull/56. I imagine this would need to go into a later release because of the compatibility issues.

**Comment by Zopieux** [comment]
Wow, completely forgot about this! I should setup some kind of TODO for Github…

Nice progress though, I'll have a look.
