### ISSUE TITLE
For more understanding with backends.default.ResendactivationView exception process.

### ISSUE THREAD

**Issue by quroom** [macropin/django-registration#404]
Currently, Regardless if resend_activation is successful, display the same confirmation template.
I think we need specific message if view process doesn't pass all process.

I think we can make 5 conditions and they all have different output message.

1. Perfectly success.
2. ObjectDoesnotExist.
3. MultipleOjbectReturned
4. User is already activated
5. Activation key is expired.

Each statement should have different message for more clear.

I guess we can make branch code for catch unvalid situation in ```models.RegistrationManager```,
Maybe we have to return some state value and error message as dict type.
And then we can proceed that message in ```views.ResendActivationView.form_valid```
like we can pass error page with different message.
It could make more clear user understanding.
How do you think?
If it's acceptable, I will make pr someday.
Or let me know more acceptable way , I will try it as you are going to explain.

**Comment by joshblum** [comment]
@quroom your proposal sounds reasonable, you can make a PR if you'd like
