### ISSUE TITLE
Show exception message for resend activation email.

### ISSUE THREAD

**Issue by quroom** [macropin/django-registration#410]
https://github.com/macropin/django-registration/blob/d770e7fb8c6cbac1c06feab8b10a935c54aa6fad/registration/models.py#L215

There are some logics for exception whether to sends mail or not.
But there is no exception message.
I think it's better to show exact message in form page.

Like as already defined process.
1. NoObject
2. MultipleObjectsReturns
3. already activated
4. key expired

Each statement should return different value to check Excpetion type in form.
Does it make sense?

If it is, I will make PR.

**Comment by joshblum** [comment]
sure

**Comment by quroom** [comment]
@joshblum , I sent PR#411
Please look up only logic for code.
I will clean up code and add more detail code.

**Comment by quroom** [comment]
Same reason as #411
