### ISSUE TITLE
Changing default_auto_field for RegistrationProfile

### ISSUE THREAD

**Issue by michalnik** [macropin/django-registration#413]
After upgrade to Django 3.2.x this warning started to appear with `django-admin run` command.
```bash
System check identified some issues:

WARNINGS:
registration.RegistrationProfile: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```

It is simply solvable with adding `default_auto_field` to model RegistrationProfile with value `django.db.models.AutoField`

**Comment by KommuSoft** [comment]
This should be put on an app config, not the model: it does not take to that account afaik?
