### ISSUE TITLE
Rename master branch to main 

### ISSUE THREAD

**Issue by macropin** [macropin/django-registration#425]
I propose to rename the `master` branch to `main`  

@dicato @joshblum  Do you foresee any issues (apart from the need to update local checkouts)?

**Comment by joshblum** [comment]
@macropin sgtm! There are a few docs with the branch name hardcoded that would have to be updated but no meaty issues come to mind

**Comment by macropin** [comment]
The change has been made. Please update your local repos: 

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
