### ISSUE TITLE
'AuthUser' object has no attribute 'backend'

### ISSUE THREAD

**Issue by TaqiOfficial** [macropin/django-registration#45]
I have customize my User model as describe in this article `http://buildthis.com/customizing-djangos-default-user-model/`. When I register new user then it successfully added to the record but after that error arises `'AuthUser' object has no attribute 'backend'`?

**Comment by AMeng** [comment]
I'm not able to reproduce this. Can you provide a traceback?

**Comment by AMeng** [comment]
@TaqiOfficial are you still seeing this with `django-registration-redux==1.2c1`?

**Comment by TaqiOfficial** [comment]
@AMeng em' using  django-registration-redux==1.1

**Comment by AMeng** [comment]
@TaqiOfficial would you mind testing with `1.2c1`?

**Comment by macropin** [comment]
This is presumed fixed in v1.2.
