### ISSUE TITLE
Make email paths variable

### ISSUE THREAD

**Issue by mcrowson** [macropin/django-registration#60]
It would be great if I could pass a template path for the activation email. Currently they are hard coded into the model.

https://github.com/macropin/django-registration/blob/master/registration/models.py

**Comment by macropin** [comment]
What's the use case for this requirement?

**Comment by mcrowson** [comment]
I would like to keep my emails in a single folder (emails) but with the paths hard coded I have to have the registration emails in the hard coded folder. I am already subclassing anyway to specify a template path, so it would be nice if this were just another variable to set for the subclass.

**Comment by dicato** [comment]
Fixed by #74
