### ISSUE TITLE
Activation failed - email clients likely pre-fetching the activation URL?

### ISSUE THREAD

**Issue by dicato** [macropin/django-registration#70]
Has anyone else run into email clients, specifically web based ones, pre-fetching the activation URL? This causes the User's email to be verified and therefore activated. When the User subsequently requests the activation URL, they are presented with a failure message, but their account has actually already been activated.

Given the design of setting the activation key to `ALREADY_ACTIVATED`, and passing the requested activation key back to the activation complete view upon failure, I don't see a straightforward way to distinguish between failures due to the User already being activated and every other failure scenario.

**Comment by macropin** [comment]
I've also personally had users complain that they received an error, when it was most likely that they double clicked the link.

**Comment by dicato** [comment]
@macropin I'm working on a fix and will hopefully have a pull request up later today :smile:

**Comment by macropin** [comment]
I've merged in the changes. Sorry for the delay. I'm pretty busy these days, so I can only give the code a once over and go with the merge and hope approach. On your head if it breaks things for other people :smile: .

**Comment by dicato** [comment]
:smile: I understand.

I've been running that branch in production since June when I made the pull request. It's been solid. Hopefully if people run into issues they report them here and I can help!
