### ISSUE TITLE
Unique email by default

### ISSUE THREAD

**Issue by vikas-parashar** [macropin/django-registration#71]
It's basic requirement for registration so one can't register multiple times using same email account.
It would be great if you merge `RegistrationFormUniqueEmail` with `RegistrationForm` in . You can provide a class like 'RegistrationFormNonUniqueEmail` if someone don't want unique email which is a rare case.
https://github.com/macropin/django-registration/blob/master/registration/forms.py

Thanks

**Comment by stringsonfire** [comment]
It would make more sense to require unique emails as standard

**Comment by dicato** [comment]
In my opinion, this is outside the scope of this Django application. Fortunately, this is [already supported](http://django-allauth.readthedocs.org/en/latest/configuration.html) by [django-allauth](http://www.intenct.nl/projects/django-allauth/).
