### ISSUE TITLE
how to add new feilds in registration form?

### ISSUE THREAD

**Issue by remazevs** [macropin/django-registration#73]
hi i m new in django ...i made registration form fro use of your code..and iits works..but i have add new feilds in forms ..how can i add..? ..pls help

**Comment by DrJackilD** [comment]
You can make subclass form (inherited from RegistrationForm), create some fields and add it. When you did it, make new class in views, inherited from RegistrationView of simple, or default backend, and override form_class variable with your form class. When you did it, make change in your urls.py, something like url(r'^accounts/register', YourViewClass.as_view, name='registration_register'), and place it BEFORE django-registration declaration.

Some examples:

forms.py:
```python
class UserProfileRegistrationForm(RegistrationForm):
    first_name = forms.CharField(max_length=15, label='First name')
    last_name = forms.CharField(max_length=15, label='second name')
    date_of_birth = forms.DateField(label='Date of birth',
                                    widget=SelectDateWidget(years=[y for y in range(1950,
                                                                                    datetime.datetime.now().year-17)],
                                                            attrs=({'style': 'width: 33%; display: inline-block;'})),)

    class Meta:
        model = YourUserModel
        fields = (UsernameField(), "email", 'first_name', 'last_name',
                  'date_of_birth')
```

views.py
```python
class UserProfileRegistration(RegistrationView):
    form_class = UserProfileRegistrationForm
```

urls.py
```python
url(r'^accounts/register/$', social.views.UserProfileRegistration.as_view(), name='registration_register'),
url(r'^accounts/', include('registration.backends.simple.urls')),
```

Hope it helps

**Comment by remazevs** [comment]
thanks for replay...its works

**Comment by aj07mm** [comment]
@DrJackilD , from where `social` comes from on `urls.py`?

**Comment by aj07mm** [comment]
@DrJackilD , in fact what is need is this whole bunch of code:
without `register` nothing happen and redirect don't work, it throws an error

```
class UserProfileRegistration(RegistrationView):
	success_url = '/'
	form_class = UserProfileRegistrationForm

	def register(self, form):
		"""
		Implement user-registration logic here.

		"""
		User = UserModel()
		user = User.objects.create_user(
            username = form.cleaned_data['username'],
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password1']
        )
		UserProfile.objects.create(
			user=user,
			name = form.cleaned_data['username'],
			cpf = form.cleaned_data['cpf'],
			created_at  = models.DateTimeField(auto_now_add=True)
		)
		if not self.registration_allowed():
			return redirect(self.disallowed_url)
		return redirect(self.get_success_url(user))
```

**Comment by aj07mm** [comment]
and the autologin with this piece of code `REGISTRATION_AUTO_LOGIN` is not working

**Comment by jholms** [comment]
I am getting an error.

fields = (UsernameField(), "email", 'first_name', 'last_name', NameError: name 'UsernameField' is not defined

What do I need to do to rectify?

It wouldn't let me comment.

**Comment by dicato** [comment]
@jholms `UsernameField` is not a standard field. If you are inheriting from the right base class form you should not define `username` as a field.

**Comment by brunoliveira8** [comment]
@aj07mm I didn't add register() and it works. The @DrJackilD's code works fine for me.
