### ISSUE TITLE
Set REGISTRATION_EMAIL_SUBJECT_PREFIX default to EMAIL_SUBJECT_PREFIX

### ISSUE THREAD

**Issue by ttttian** [macropin/django-registration#75]
With the same logic as `getattr(settings, 'REGISTRATION_DEFAULT_FROM_EMAIL', settings.DEFAULT_FROM_EMAIL)`, `getattr(settings, 'REGISTRATION_EMAIL_SUBJECT_PREFIX', settings.EMAIL_SUBJECT_PREFIX)` instead of current `getattr(settings, 'REGISTRATION_EMAIL_SUBJECT_PREFIX', '')` would be more compatible to the Django default settings.

https://github.com/macropin/django-registration/blob/master/registration/models.py

**Comment by dicato** [comment]
I believe this has been fixed in master.
