### ISSUE TITLE
Registered users and activation keys are not appearing in admin.

### ISSUE THREAD

**Issue by FroggyRiseman** [macropin/django-registration#77]
I'm new to programming and might not ask correctly about my exact issue.

When I register users they are not appearing here `/admin/registration/registrationprofile/`.
Because of this there is also no activation keys and no activation emails being sent. I've followed the [official doc](https://django-registration-redux.readthedocs.org/en/latest/index.html), used the [Tango With Django](http://www.tangowithdjango.com/book17/chapters/login_redux.html) setup for registration-redux, and checked out 2 videos from YouTube ([one](https://www.youtube.com/watch?v=qkFWkOw-ByU), and [two](https://www.youtube.com/watch?v=qbvMC1TEKHM)).

Any help and/or explanation on why I have encountered this problem?

**Comment by dicato** [comment]
@FroggyRiseman are you still having this issue?
