### ISSUE TITLE
Cannot include the urls with namespace

### ISSUE THREAD

**Issue by 5xum** [macropin/django-registration#81]
Right now, adding 

url(r'^accounts/', include('registration.backends.default.urls', namespace='accounts')),

to my urls.py file will cause an error anywhere in my template where I use {% url 'accounts:auth_password_change' %}

This is probably because of the line

{'post_change_redirect': reverse_lazy('auth_password_change_done')}

which causes the template engine to go reverse 'auth_password_change_done' when it should actually reverse 'accounts:auth_password_change_done'.

**Comment by macropin** [comment]
What's the fix to pass namespace generically?

**Comment by joshblum** [comment]
@5xum you'll have to set `INCLUDE_AUTH_URLS=False` and change the call to `reverse_lazy` manually.
