### ISSUE TITLE
How to use all Forms for user registration

### ISSUE THREAD

**Issue by Sayyiditow** [macropin/django-registration#83]
Hi guys, 

I am new to this and I kinda need to use RegistrationFormUniqueEmail and RegistrationFormNoFreeEmail at the same time. I have tried to use the form class but I can only subclass  one form at a time. Is there a way to use both subclasses at the same time?

Thanks in advance

**Comment by dicato** [comment]
Why can you only subclass one `Form` at a time? You *should* be able to inherit from many.

In theory, you should be able to do this:

```python
class RegistrationFormUniquePaidEmail(RegistrationFormUniqueEmail, ResigtrationFormNoFreeEmail):

    def clean_email(self):
        # Note the return value from both `clean_email` methods is the same,

        RegistrationFormUniqueEmail.clean_email(self)
        return RegistrationFormNoFreeEmail.clean_email(self)
```

**Comment by Sayyiditow** [comment]
Hey man, thanks a lot for getting back to me ASAP. I just used this on django and it works! You are a savior! Btw, you got a spelling wrong on:

class RegistrationFormUniquePaidEmail(RegistrationFormUniqueEmail, ResigtrationFormNoFreeEmail): Second class is ReGis...

Anyways, here's how I implemented both for those who wanna know. I used both in urls.py however you can do half in forms.py and the url part in urls.py.

.................
from registration.forms import RegistrationFormUniqueEmail, RegistrationFormNoFreeEmail
from registration.backends.default.views import RegistrationView

class RegistrationFormUniquePaidEmail(RegistrationFormUniqueEmail, RegistrationFormNoFreeEmail):

    def clean_email(self):
        # Note the return value from both `clean_email` methods is the same,
        # so just return the second.
        RegistrationFormUniqueEmail.clean_email(self)
        return RegistrationFormNoFreeEmail.clean_email(self)

urlpatterns = [...
url(r'^accounts/register/$',
        RegistrationView.as_view(form_class = RegistrationFormUniquePaidEmail),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.default.urls')),

] 

Next step is to get more free emails as part of the "bad_domains"

Thanks a lot!

**Comment by dicato** [comment]
You're welcome, glad I could help! :+1:

**Comment by dicato** [comment]
@macropin you can close this!
