### ISSUE TITLE
django.core.urlresolvers.NoReverseMatch: Reverse for 'password_reset_confirm'

### ISSUE THREAD

**Issue by ishaq** [macropin/django-registration#85]
**Django:** 1.8
**Python:** 3.4

When a user tries to reset password, it throws exception:

```
django.core.urlresolvers.NoReverseMatch: Reverse for 'password_reset_confirm' with
    arguments '()' and keyword arguments '{'token': '444-9887c242917d1b6b7368',
    'uidb64': b'Mg'}' not found. 0 pattern(s) tried: []
```

[This thread](https://stackoverflow.com/questions/19985103/django-1-6-and-django-registration-built-in-authentication-views-not-picked-up) on Stackoverflow solved it for me.

>The reason for this error is that the _django.contrib.auth.views_ use different url names than the _registration.auth_urls_ ones. To patch this problem, override the default urls until _django-registration-redux_ gets updated for django 1.6, and use the same names as Django.

```python
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',

      #override the default urls
      url(r'^password/change/$',
                    auth_views.password_change,
                    name='password_change'),
      url(r'^password/change/done/$',
                    auth_views.password_change_done,
                    name='password_change_done'),
      url(r'^password/reset/$',
                    auth_views.password_reset,
                    name='password_reset'),
      url(r'^password/reset/done/$',
                    auth_views.password_reset_done,
                    name='password_reset_done'),
      url(r'^password/reset/complete/$',
                    auth_views.password_reset_complete,
                    name='password_reset_complete'),
      url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                    auth_views.password_reset_confirm,
                    name='password_reset_confirm'),

      #and now add the registration urls
      url(r'^accounts/$', include('registration.backends.default.urls')),
)
```

**Comment by dicato** [comment]
@ishaq I usually include auth URLs in the same way you describe.

Did you see [this documentation about registration.auth_urls](https://django-registration-redux.readthedocs.org/en/latest/faq.html#configuration)? Does it help?

**Comment by ishaq** [comment]
@dicato thanks for the link to the documentation. I had seen it though, It was not helpful because it doesn't say password reset function will not work unless one puts additional patterns in url conf. It was only after seeing the exception that I realised some url patterns are missing.

please note that the issue is not that I wasn't including auth_urls (they are included by default with the *registration.backends.default.urls*. The issue is that the url patterns in auth_urls are named differently from what django expects e.g. `auth_password_reset_confirm` instead of `password_reset_confirm`.

**Comment by dicato** [comment]
@ishaq thanks for the clarification. I think I understand. I'm still uncertain if there is actually anything to fix. I thought that [this code addressed the issue for Django 1.6](https://github.com/macropin/django-registration/blob/bfe6426c64171f8f3afb5980fe58b74bb0fae732/registration/auth_urls.py#L65).

I just tested the [test application](https://github.com/macropin/django-registration/tree/bfe6426c64171f8f3afb5980fe58b74bb0fae732/test_app) against Python 2.7.10 and Django 1.8.3 and the password reset process works properly. Could you maybe confirm this as well?

Sorry for being a bit confused about the issue!

**Comment by ishaq** [comment]
@dicato sorry for replying late. I have tested the test application against Django 1.8.3 (both Python 2.7.10 and Python 3.4.2). It works.

Therefore the problem must be with just my setup. I'll figure it out, Closing this. Sorry :smile:

**Comment by dicato** [comment]
@ishaq no problem! I'm glad you figured it out. If you end up determining the cause locally, please let me know!

**Comment by ishaq** [comment]
@dicato the issue was that _django.contrib.admin_ appeared above _registration_ in `INSTALLED_APPS` array in `settings.py`.

It was also using admin templates for password reset and password change. So, if one notices those templates being used, _django.contrib.admin_ should be immediately moved below _registration_ in `INSTALLED_APPS` array to use correct templates and to avoid this issue.

**Comment by dicato** [comment]
@ishaq thanks for the update! I'm wondering if there is a good way to explain that in the documentation? Ordering on installed apps matters.
