### ISSUE TITLE
Syndb and south migration fails with Django 1.5.11: You have no migrations for the 'registration' app. You might want some.

### ISSUE THREAD

**Issue by mick-t** [macropin/django-registration#87]
Hi,

I'm using Django 1.5.11 and I've installed django-registration-redux 1.2, 1.2c0, and 1.3a0 and neither syncdb nor south migrations appear to be working and running the South migration command fails with:

``` You have no migrations for the 'registration' app. You might want some. ```

'register' is added to INSTALLED_APP.

Here's the output from syncdb:

```
$ python manage.py syncdb
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 10 object(s) from 1 fixture(s)

Synced:
 > grappelli
 > radmin
 > admin_timeline
 > singleton_models
 > adminactions
 > django.contrib.admindocs
 > django.contrib.admin
 > south
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.messages
 > django.contrib.markup
 > django.contrib.staticfiles
 > captcha
 > honeypot
 > publications
 > django.contrib.comments
 > debug_toolbar
 > djcelery_email
 > rest_framework

Not synced (use migrations):
 - reversion
 - explorer
 - sbgrid_contacts
 - sbgrid
 - custom
 - flatpages
 - django_extensions
 - registration
(use ./manage.py migrate to migrate these)

```

And the output from running the South migrate command:

```
$ python manage.py migrate

Running migrations for reversion:
- Nothing to migrate.
 - Loading initial data for reversion.
Installed 0 object(s) from 0 fixture(s)
Running migrations for explorer:
- Nothing to migrate.
 - Loading initial data for explorer.
Installed 0 object(s) from 0 fixture(s)
Running migrations for custom:
- Nothing to migrate.
 - Loading initial data for custom.
Installed 0 object(s) from 0 fixture(s)
Running migrations for flatpages:
- Nothing to migrate.
 - Loading initial data for flatpages.
Installed 0 object(s) from 0 fixture(s)
Running migrations for django_extensions:
- Nothing to migrate.
 - Loading initial data for django_extensions.
Installed 0 object(s) from 0 fixture(s)
? You have no migrations for the 'registration' app. You might want some.
```

This is in a virtualenv and I can see the migration files in the virtualenv:

```
 ls ~/.virtualenvs/sbgrid_v2/lib/python2.7/site-packages/registration/migrations/
0001_initial.py		0001_initial.pyc	__init__.py		__init__.pyc
```

**Comment by mick-t** [comment]
[README] (https://github.com/macropin/django-registration/blob/master/README.rst) says it works on Django 1.4+:

> It requires a functional installation of Django 1.4 or newer, but has no other dependencies.

**Comment by mick-t** [comment]
I created a fork and recreated the South migrations:

https://github.com/sbgrid/django-registration/tree/master/registration/south_migrations

These work for me, but what can I do to help with this?

**Comment by mick-t** [comment]
This commit by mauler should resolve the issue:

* https://github.com/macropin/django-registration/pull/78/commits

Can you please merge this change so that I don't have to use a fork? :) 

Thanks.

**Comment by mick-t** [comment]
Bump.

**Comment by macropin** [comment]
Merged.

**Comment by mick-t** [comment]
My bad! I didn't read through his commit in detail and I assumed it would work -- it doesn't because it has a models that don't exist in Django 1.5 or later and are what I assume custom models that mauler created for his own purposes:

These custom models all begin with "core." such as:

* core.accommodation
* core.accommodationtype
* core.attraction
* ...

I dug through the Django source and there's no such types, nor in the Django-registration-redux source code. I'll create a pull request, which I believe will resolve this.

Thanks
