### ISSUE TITLE
Migration failure when upgrading from 1.1 to 1.2

### ISSUE THREAD

**Issue by seddonym** [macropin/django-registration#88]
When I upgraded django-registration-redux from 1.1 to 1.2, and then ran `./manage.py migrate`, I get the following error:

    django.db.utils.ProgrammingError: relation "registration_registrationprofile" already exists

This is because the table was already created via a syncdb command, before the migrations were added to the codebase.

The migrations can be faked manually but I wonder if there is a way of handling this in your codebase.

Thanks for all your work on this package by the way!

**Comment by macropin** [comment]
I don't believe it is possible to handle this other than to fake the migration. Would you mind sending a PR to document this issue?

**Comment by dicato** [comment]
@seddonym is this still valid on the latest release?

**Comment by seddonym** [comment]
@dicato I'm afraid I don't have time to check this for 1.3 at the moment, sorry!

**Comment by dicato** [comment]
@seddonym not a problem. I'm going to close the issue. Please feel free to re-start the conversation.
