### ISSUE TITLE
Upgrade guide in documentation & Releases page conflict with each other

### ISSUE THREAD

**Issue by martey** [macropin/django-registration#89]
The [upgrade guide in the documentation](https://github.com/macropin/django-registration/blob/9ba4cc7f1cfc524b980739e8d96470848fd6986a/docs/upgrade.rst) and the [information on the Releases page](https://github.com/macropin/django-registration/releases) conflict with each other. For example:
- The documentation claims that 1.2 changes the parameters of the register method in RegistrationView; this is not mentioned on the Releases page
- The Releases pages claims that 1.2 requires a `base.html` template; the documentation claims that 1.1 requires it.
- The documentation claims that 1.1 requires HTML email templates. The Releases page does not mention this, but claims that at least one HTML email template can be disabled by setting `REGISTRATION_EMAIL_HTML` to False. The documentation does not mention `REGISTRATION_EMAIL_HTML` at all.

I think it would be easier for people to upgrade (and for everything to be maintained) if the changelog and backwards incompatible changes were stored in one (and only one) location.

**Comment by macropin** [comment]
Happy to take a pull request to address these issues. Thanks.

**Comment by martey** [comment]
I explicitly created an issue instead of making a pull request for this because any solution requires buy-in by the person creating releases so that this doesn't recur in the future:

  - The Releases page is not part of the repository and currently contains misleading information. Any pull request that I or someone else submit will not fix this.
  - It's still not clear if you would prefer backwards-incompatible changes to live in the documentation's upgrade guide, the CHANGELOG, or somewhere else.

**Comment by macropin** [comment]
Can you please let me know if / where conflicts exist. I've updated the github releases to refer to the changelog.

**Comment by dicato** [comment]
There has been many small cleanups. Is this issue still a problem or should it be closed?

**Comment by martey** [comment]
I think the only remaining problem is that backward-incompatible changes are listed in both the changelog and the "upgrade guide" in the documentation. Even if the two documents both include the same information now, there is no guarantee that they will not accidentally become out of sync in the future.

I think the upgrade guide has outlived its usefulness (since django-registration-redux now includes multiple backwards-incompatible changes that prevents it from being a drop-in solution for django-registration) and that the additional information about new features contained in the changelog make it the most useful document.

Let me know if you would like me to submit a pull request removing the upgrade guide/pointing it at the changelog.

**Comment by dicato** [comment]
@martey please do!

**Comment by joshblum** [comment]
@martey are you still interested in working on this?

**Comment by joshblum** [comment]
@martey https://github.com/macropin/django-registration/pull/296 should handle the issues you've outlined. Closing this for now, let me know if you would like to add any clarifications!
