### ISSUE TITLE
Passing extra context to registration form

### ISSUE THREAD

**Issue by amitbend** [macropin/django-registration#91]
Hi,
I'm struggling with this for a while, , and i hope anyone can help me.

I'm trying to pass extra context (model objects) to 
``` registration/registration_form.html ```

i red the docs few times and tried multiple solutions but nothing works. :(

**Comment by dicato** [comment]
If you literally want to pass extra data to `context` for use in the template, you can subclass the `RegistrationView` you are using and add the appropriate data in `get_context_data`.

For example:

```python
class CustomRegistrationView(RegistrationView):
    def get_context_data(self, **kwargs):
        context = super(RegistrationView, self).get_context_data(**kwargs)
        # add your additional data here
        context['foo'] = 'bar'
        return context
```

**Comment by dicato** [comment]
If you literally want to pass extra data to `context` for use in the template, you can subclass the `RegistrationView` you are using and add the appropriate data in `get_context_data`.

For example:

```python
class CustomRegistrationView(RegistrationView):
    def get_context_data(self, **kwargs):
        context = super(RegistrationView, self).get_context_data(**kwargs)
        # add your additional data here
        context['foo'] = 'bar'
        return context
```

**Comment by amitbend** [comment]
Thanks you dicato!
it works.

**Comment by dicato** [comment]
:+1: You're welcome!

@macropin feel free to close this issue.
