### ISSUE TITLE
Drop support for unsupported Django versions

### ISSUE THREAD

**Issue by timgraham** [macropin/django-registration#92]
Django 1.6 is unsupported and 1.4 will be unsupported October 1. Is it time to drop support for these versions?

**Comment by macropin** [comment]
Yes, that's the plan. Happy to take a PR to adjust the documentation, tests etc for the next release.

**Comment by jamesturk** [comment]
working on this (and adding 1.9 support)

would this be OK for support?

Python 2.7, 3.4, 3.5
Django 1.7, 1.8, 1.9

1.7 is about to become unsupported (December) but doesn't seem that hard to support compared to 1.6

rough WIP branch here: https://github.com/jamesturk/django-registration/tree/drop-old-versions

**Comment by jamesturk** [comment]
similarly, realized in doing this that 3.3 isn't hard to keep but is dropped by Django 1.9 and later.

glad to submit a PR with or without 3.3 and/or 1.7 depending on what you all prefer

**Comment by macropin** [comment]
I haven't seen much use of Python versions other than 2.7 / 3.4. I don't think the inclusion of 3.3 or loss is a big deal either way - I don't think we're using any features that would make it impossible to not support 3.3 but then again what's the point if there are no users.. Django 1.7, 1.8, 1.9 seems sane. And lets go with Python 2.7, 3.4, 3.5.

**Comment by dicato** [comment]
I agree with supporting those versions.

**Comment by jamesturk** [comment]
left 3.3 in for now because it was one extra import, PR is #117

**Comment by macropin** [comment]
Thanks for this PR merged.
