### ISSUE TITLE
Question: Would changing an email fit in this project?

### ISSUE THREAD

**Issue by stringsonfire** [macropin/django-registration#93]
Given a new email also needs to be activated, and the mechanism is in place here, is that something to think about including in django-registration-redux, or is it beyond the scope of this project?

**Comment by macropin** [comment]
Are you proposing adding the workflows for validating a change of email address? Yes, I would think that it fits within the domain of this project.

**Comment by stringsonfire** [comment]
As a feature suggestion, yes. Unfortunately, I'm currently far from skilled enough to implement something like that myself (full disclosure: I'm not really a developer)

**Comment by dicato** [comment]
I agree this would be useful. I often run into the scenario where Users are allowed to change their email. Once changed, their email is technically unverified, but an Admin needs to manually push the User through the verification process.

I'd be happy to work on this.

**Comment by stringsonfire** [comment]
Awesome, thanks!

Would similar functionality for Username fit here as well?

Although it doesn't require activation, I can imagine there is more involved, for example limiting the number of times a username can be changed per amount of time, or maybe saving the previous username for a certain amount of time, to use for redirection and to prevent other users from using it for a certain amount of time?

**Comment by dicato** [comment]
I don't think so. Changing Username is not related to the User registration process in my opinion. Email verification is; that data is literally saved on the Registration model.

**Comment by dicato** [comment]
After some debate, here is my plan for this:

* connect a `pre_save` signal to the `User` model
* in said signal compare the email address on the instance with the email address in the database using said instance's ID for lookup
* if said emails differ, set `RegistrationProfile.activated` to `False` and kickoff the activation process

There are a bunch of challenges with re-starting the activation process (key reuse, etc) that I need to think though, but I believe the rough plan above should work.

I think, at this point, this is something that should be on by default and not developer configurable.

**Comment by stringsonfire** [comment]
Reusing the process as is would raise some UX issues. For example, I change my email address, activate my email, and I'm taken to the same page I saw when I first activated my account, so either

1. this page cannot contain information only relevant to new users
2. new views and templates are required to separate this, or
3. an additional redirect is needed away from the activated page if the user changed their email (so that information would need to be stored). Given not all developers use the same form of notifications, I'm not sure how you could confirm with feedback to the user that the email has been changed with that last option. New views/templates seems the most flexible.

There's also the issue of users not being 'active' until they confirm their new email address. Is this a requirement for `@login_required`? This would also be a hit on other code that checked if a user is active, so either way this could break a lot of apps.

What about a `new_email` field (blank=true, null=true) to hold the new email? A `post_save` could pick up when `new_email` has been set to not None, and fire off an activation process. In the meantime, `email` is still used as normal`. When the `new_email` is confirmed, the contents of `new_email` overwrites `email`, and `new_email` is set to `None` again. I'm not sure if this should be in `post_save` or in a view. Would still need new templates/views for UX purposes as above.

**Comment by dicato** [comment]
You are correct regarding re-activation; the emails and views will currently have the same content as initial registration and activation. I was considering refactoring the related code to allow for different templates to be passed in for rendering in the emails and views. I need to poke around a bit to see how that would work.

I was *not* going to make the account inactive on email change. I believe that will make for a poor user experience,

I was trying to not add any additional fields to `RegistrationProfile`. I don't want that model to become the catch all for User management - there is a `User` model already. I really appreciate your feedback and am going to spend some more time thinking about the design of this. I am curious how much of this is potentially implemented in [django-allauth](https://github.com/pennersr/django-allauth) so I am going to look at that as well.

**Comment by dicato** [comment]
Revisiting this, I no longer believe this should be added to this project. This functionality already exists in django-allauth.

Multiple users have told me they specifically like this application because of it's simplicity. I'm going to close this issue.
