### ISSUE TITLE
Request: Optionally validate Username uniqueness with iexact

### ISSUE THREAD

**Issue by stringsonfire** [macropin/django-registration#95]
Having read [this issue](https://code.djangoproject.com/ticket/2273) raised at the Django repository, the Django team aren't willing to fix this, citing some strange reasons.

Currently, StringsonFire, STRINGSonfire and stringsONfire would all be valid usernames in the same database, even though, when case is ignored, they're the same. Given usernames are a simple and visually friendly way to identify users within a webapp, I've found an additional test to consider the above three as violating the unique constraint to be useful.

I've written this validator, which uses both UserModel() and UsernameField() to align with the rest of django-registration:

    from django.core.exceptions import ValidationError
    from django.utils.translation import ugettext_lazy as _

    from registration.users import UserModel, UsernameField

    User = UserModel()

    def username_case_insensitive_unique_validator(value):
        kwargs = {'{0}__{1}'.format(UsernameField(), 'iexact'): value}
        if User.objects.filter(**kwargs):
            raise ValidationError(_('A user with that username already exists.'), code='invalid')

I wonder if this could be included, perhaps with a setting `USERNAME_CASE_INSENSITIVE_VALIDATION = True`, or, perhaps like `RegistrationFormUniqueEmail`, where this is already implemented for emails, this could sit in another form?

**Comment by macropin** [comment]
I think it's a good idea. As this is a common enough problem / use case. Also would be a good idea to be able to handle the issue of email addresses as usernames. But it would require a nice PR, with tests, documentation etc.

**Comment by dicato** [comment]
I think this is better suited to be solved (if not already) in a third-parth authentication package, such as django-allauth.

**Comment by joshblum** [comment]
@dicato @macropin should we close this for now? django-allauth seems to handle this issue: https://github.com/pennersr/django-allauth/blob/8dbd4dd00f7f66e4d2599410932f06c4d0f08b6f/allauth/account/adapter.py#L269

**Comment by dicato** [comment]
Yes, I don't think we should add this to django-registration. It's a great example of essentially duplicating code from other popular projects.
